quiz_questions = [
{"category": "Công nghệ", "question": "Ngôn ngữ lập trình nào được coi là nền tảng của hệ điều hành Unix?", "options": ["A) C", "B) Java", "C) Python", "D) Assembly"], "answer": "A"},
{"category": "Khoa học", "question": "Ai là người phát minh ra bóng đèn điện?", "options": ["A) Alexander Graham Bell", "B) Thomas Edison", "C) Nikola Tesla", "D) Benjamin Franklin"], "answer": "B"},
{"category": "Khoa học", "question": "Hợp chất nào tạo nên khí nhà kính chủ yếu?", "options": ["A) CO2", "B) O2", "C) N2", "D) H2"], "answer": "A"},
{"category": "Sinh học", "question": "Cơ quan nào đảm nhiệm việc lọc máu trong cơ thể người?", "options": ["A) Gan", "B) Thận", "C) Tim", "D) Phổi"], "answer": "B"},
{"category": "Sinh học", "question": "Nước chiếm khoảng bao nhiêu phần trăm khối lượng cơ thể người?", "options": ["A) 50%", "B) 60%", "C) 70%", "D) 80%"], "answer": "B"},
{"category": "Công nghệ", "question": "Hệ điều hành Android được phát triển bởi ai?", "options": ["A) Google", "B) Apple", "C) Microsoft", "D) Samsung"], "answer": "A"},
{"category": "Lịch sử", "question": "Ai là người đầu tiên phát minh ra điện thoại?", "options": ["A) Thomas Edison", "B) Alexander Graham Bell", "C) Nikola Tesla", "D) Michael Faraday"], "answer": "B"},
{"category": "Hóa học", "question": "Nguyên tố có ký hiệu Pb là gì?", "options": ["A) Bạc", "B) Chì", "C) Thiếc", "D) Kẽm"], "answer": "B"},
{"category": "Địa lý", "question": "Đại dương nào nhỏ nhất trên Trái Đất?", "options": ["A) Đại Tây Dương", "B) Bắc Băng Dương", "C) Ấn Độ Dương", "D) Thái Bình Dương"], "answer": "B"},
{"category": "Thiên văn", "question": "Thời gian ánh sáng đi từ Mặt Trời đến Trái Đất là bao lâu?", "options": ["A) 4 phút", "B) 8 phút 20 giây", "C) 10 phút", "D) 12 phút"], "answer": "B"},
{"category": "Sinh học", "question": "Cây lúa thuộc họ thực vật nào?", "options": ["A) Họ Đậu", "B) Họ Lúa", "C) Họ Cúc", "D) Họ Cói"], "answer": "B"},
{"category": "Tin học", "question": "Trong hệ nhị phân, số 10 tương đương với số nào trong hệ thập phân?", "options": ["A) 1", "B) 2", "C) 3", "D) 4"], "answer": "B"},
{"category": "Vật lý", "question": "Ai là người phát minh ra thuyết tương đối hẹp?", "options": ["A) Newton", "B) Einstein", "C) Maxwell", "D) Planck"], "answer": "B"},
{"category": "Vật lý", "question": "Vận tốc ánh sáng trong chân không là bao nhiêu?", "options": ["A) 300,000 km/s", "B) 150,000 km/s", "C) 200,000 km/s", "D) 250,000 km/s"], "answer": "A"},
{"category": "Thiên văn", "question": "Trong hệ mặt trời, hành tinh nào có ngày dài nhất?", "options": ["A) Sao Thủy", "B) Sao Kim", "C) Sao Hỏa", "D) Sao Thổ"], "answer": "B"},
{"category": "Sinh học", "question": "Loài động vật nào được xem là thông minh nhất sau con người?", "options": ["A) Tinh tinh", "B) Cá heo", "C) Voi", "D) Quạ"], "answer": "B"},
{"category": "Hóa học", "question": "Công thức hóa học của axit sulfuric là gì?", "options": ["A) HCl", "B) H2SO4", "C) HNO3", "D) H2CO3"], "answer": "B"},
{"category": "Thiên văn", "question": "Ai là người đầu tiên sử dụng kính thiên văn để quan sát bầu trời?", "options": ["A) Kepler", "B) Galileo", "C) Newton", "D) Copernicus"], "answer": "B"},
{"category": "Thiên văn", "question": "Hành tinh nào có vành đai nổi bật nhất?", "options": ["A) Sao Mộc", "B) Sao Thổ", "C) Sao Thiên Vương", "D) Sao Hải Vương"], "answer": "B"},
{"category": "Sinh học", "question": "Chất nào trong không khí giúp con người hô hấp?", "options": ["A) Nitơ", "B) Oxy", "C) Cacbon", "D) Hidro"], "answer": "B"},
{"category": "Khoa học", "question": "Phát minh nào giúp con người truyền tín hiệu không dây?", "options": ["A) Đèn điện", "B) Radio", "C) Điện thoại", "D) Máy ảnh"], "answer": "B"},
{"category": "Địa lý", "question": "Thủ đô của Thụy Sĩ là gì?", "options": ["A) Zurich", "B) Bern", "C) Geneva", "D) Basel"], "answer": "B"},
{"category": "Văn học", "question": "Tác phẩm 'Đất rừng phương Nam' của ai?", "options": ["A) Đoàn Giỏi", "B) Nguyễn Minh Châu", "C) Tô Hoài", "D) Nam Cao"], "answer": "A"},
{"category": "Tin học", "question": "Trong lập trình, ký hiệu '==' có nghĩa là gì?", "options": ["A) Gán giá trị", "B) So sánh bằng nhau", "C) Không bằng", "D) Hoặc"], "answer": "B"},
{"category": "Hóa học", "question": "Nguyên tố nào có số hiệu nguyên tử là 1?", "options": ["A) Oxy", "B) Hidro", "C) Helium", "D) Carbon"], "answer": "B"},
{"category": "Sinh học", "question": "Cơ quan nào điều khiển mọi hoạt động của cơ thể người?", "options": ["A) Tim", "B) Não", "C) Gan", "D) Thận"], "answer": "B"},
{"category": "Công nghệ", "question": "Ai được mệnh danh là cha đẻ của Internet?", "options": ["A) Tim Berners-Lee", "B) Bill Gates", "C) Vinton Cerf", "D) Steve Jobs"], "answer": "C"},
{"category": "Điện ảnh", "question": "Bộ phim 'Titanic' giành giải Oscar năm nào?", "options": ["A) 1995", "B) 1997", "C) 1998", "D) 1999"], "answer": "C"},
{"category": "Lịch sử", "question": "Quốc gia nào phát minh ra giấy?", "options": ["A) Ấn Độ", "B) Trung Quốc", "C) Hy Lạp", "D) Ai Cập"], "answer": "B"},
{"category": "Thiên văn", "question": "Ngôi sao nào gần Trái Đất nhất?", "options": ["A) Sao Mộc", "B) Mặt Trời", "C) Sao Kim", "D) Sao Thổ"], "answer": "B"},
{"category": "Địa lý", "question": "Quốc gia nào có nhiều múi giờ nhất?", "options": ["A) Nga", "B) Mỹ", "C) Trung Quốc", "D) Canada"], "answer": "A"},
{"category": "Sinh học", "question": "Loài sinh vật nào có khả năng tái sinh mạnh nhất?", "options": ["A) Sao biển", "B) Bạch tuộc", "C) Giun đất", "D) Cá chình"], "answer": "A"},
{"category": "Vật lý", "question": "Tần số của sóng vô tuyến đo bằng đơn vị gì?", "options": ["A) Volt", "B) Hertz", "C) Newton", "D) Pascal"], "answer": "B"},
{"category": "Giáo dục", "question": "Người Việt đầu tiên đoạt giải Nobel là ai?", "options": ["A) Chưa có", "B) Trần Đại Nghĩa", "C) Ngô Bảo Châu", "D) Hồ Chí Minh"], "answer": "C"},
{"category": "Lịch sử", "question": "Phát minh nào của Johannes Gutenberg thay đổi thế giới?", "options": ["A) Máy in", "B) La bàn", "C) Đồng hồ", "D) Kính hiển vi"], "answer": "A"},
{"category": "Tin học", "question": "Trong Tin học, RAM là viết tắt của gì?", "options": ["A) Random Access Memory", "B) Read All Memory", "C) Rapid Active Module", "D) Remote Area Memory"], "answer": "A"},
{"category": "Địa lý", "question": "Cơn bão di chuyển theo hướng nào ở Bắc bán cầu?", "options": ["A) Cùng chiều kim đồng hồ", "B) Ngược chiều kim đồng hồ", "C) Từ Nam lên Bắc", "D) Không cố định"], "answer": "B"},
{"category": "Lịch sử", "question": "Quốc gia nào phát minh ra thuốc súng?", "options": ["A) Trung Quốc", "B) Ấn Độ", "C) Hy Lạp", "D) Ai Cập"], "answer": "A"},
{"category": "Văn học", "question": "Ai là tác giả của tác phẩm 'Những người khốn khổ'?", "options": ["A) Victor Hugo", "B) Balzac", "C) Molière", "D) Dumas"], "answer": "A"},
{"category": "Hóa học", "question": "Trong hóa học, pH = 7 thể hiện môi trường gì?", "options": ["A) Axit", "B) Trung tính", "C) Bazơ", "D) Kiềm mạnh"], "answer": "B"},
{"category": "Địa lý", "question": "Nước chiếm bao nhiêu phần trăm diện tích bề mặt Trái Đất?", "options": ["A) 50%", "B) 60%", "C) 70%", "D) 80%"], "answer": "C"},
{"category": "Sinh học", "question": "Người đầu tiên phát hiện ra vi khuẩn là ai?", "options": ["A) Pasteur", "B) Leeuwenhoek", "C) Newton", "D) Mendel"], "answer": "B"},
{"category": "Thể thao", "question": "Thế vận hội Olympic hiện đại đầu tiên được tổ chức ở đâu?", "options": ["A) London", "B) Athens", "C) Paris", "D) Rome"], "answer": "B"},
{"category": "Hóa học", "question": "Kí hiệu hóa học của bạc là gì?", "options": ["A) Au", "B) Ag", "C) Al", "D) Ar"], "answer": "B"},
{"category": "Hóa học", "question": "Thành phần chính của khí tự nhiên là gì?", "options": ["A) Metan", "B) Propan", "C) Butan", "D) Etan"], "answer": "A"},
{"category": "Triết học", "question": "Nhà triết học Hy Lạp nào là thầy của Aristotle?", "options": ["A) Socrates", "B) Plato", "C) Heraclitus", "D) Pythagoras"], "answer": "B"},
{"category": "Vật lý", "question": "Tốc độ âm thanh trong không khí khoảng bao nhiêu?", "options": ["A) 200 m/s", "B) 343 m/s", "C) 500 m/s", "D) 700 m/s"], "answer": "B"},
{"category": "Hóa học", "question": "Nguyên tố nào có ký hiệu Cu?", "options": ["A) Cacbon", "B) Đồng", "C) Kẽm", "D) Thiếc"], "answer": "B"},
{"category": "Địa lý", "question": "Kinh tuyến gốc đi qua quốc gia nào?", "options": ["A) Mỹ", "B) Anh", "C) Pháp", "D) Đức"], "answer": "B"},
{"category": "Thiên văn", "question": "Hành tinh nào có mật độ lớn nhất trong hệ Mặt Trời?", "options": ["A) Trái Đất", "B) Sao Kim", "C) Sao Mộc", "D) Sao Thổ"], "answer": "A"},
{"category": "Lịch sử", "question": "Người Ai Cập cổ đại sử dụng loại chữ viết nào?", "options": ["A) Chữ tượng hình", "B) Chữ Latin", "C) Chữ Sanskrit", "D) Chữ Hy Lạp"], "answer": "A"},
{"category": "Địa lý", "question": "Quốc gia nào có diện tích nhỏ nhất thế giới?", "options": ["A) Monaco", "B) Vatican", "C) Liechtenstein", "D) San Marino"], "answer": "B"},
{"category": "Sinh học", "question": "Loài người thuộc lớp động vật nào?", "options": ["A) Lưỡng cư", "B) Thú", "C) Chim", "D) Bò sát"], "answer": "B"},
{"category": "Văn học", "question": "Tác phẩm 'Nhật ký trong tù' do ai sáng tác?", "options": ["A) Tố Hữu", "B) Hồ Chí Minh", "C) Xuân Diệu", "D) Huy Cận"], "answer": "B"},
{"category": "Hóa học", "question": "Nguyên tố nào có ký hiệu Na?", "options": ["A) Nitơ", "B) Natri", "C) Nickel", "D) Neon"], "answer": "B"},
{"category": "Địa lý", "question": "Sông nào dài nhất châu Á?", "options": ["A) Trường Giang", "B) Mekong", "C) Hồng Hà", "D) Ấn Hà"], "answer": "A"},
{"category": "Môi trường", "question": "Nguyên nhân chính gây ra biến đổi khí hậu là gì?", "options": ["A) Mưa axit", "B) Hiệu ứng nhà kính", "C) Nhiệt độ tăng do Mặt Trời", "D) Sóng thần"], "answer": "B"},
{"category": "Địa lý", "question": "Thủ đô của Việt Nam là gì?", "options": ["A) Hà Nội", "B) TP Hồ Chí Minh", "C) Đà Nẵng", "D) Hải Phòng"], "answer": "A"},
{"category": "Địa lý", "question": "Thủ đô của Canada là gì?", "options": ["A) Toronto", "B) Vancouver", "C) Ottawa", "D) Montreal"], "answer": "C"},
{"category": "Địa lý", "question": "Quốc gia có diện tích lớn nhất thế giới là?", "options": ["A) Canada", "B) Nga", "C) Trung Quốc", "D) Mỹ"], "answer": "B"},
{"category": "Địa lý", "question": "Sông dài nhất thế giới là gì?", "options": ["A) Nile", "B) Amazon", "C) Dương Tử", "D) Mississippi"], "answer": "A"},
{"category": "Địa lý", "question": "Đỉnh núi cao nhất thế giới là gì?", "options": ["A) Everest", "B) K2", "C) Kangchenjunga", "D) Lhotse"], "answer": "A"},
{"category": "Địa lý", "question": "Sa mạc lớn nhất thế giới là gì?", "options": ["A) Sahara", "B) Gobi", "C) Kalahari", "D) Atacama"], "answer": "A"},
{"category": "Lịch sử", "question": "Ai là người sáng lập triều đại nhà Nguyễn?", "options": ["A) Nguyễn Huệ", "B) Gia Long", "C) Minh Mạng", "D) Tự Đức"], "answer": "B"},
{"category": "Lịch sử", "question": "Chiến tranh thế giới thứ hai kết thúc năm nào?", "options": ["A) 1940", "B) 1943", "C) 1945", "D) 1950"], "answer": "C"},
{"category": "Lịch sử", "question": "Trận Điện Biên Phủ diễn ra năm nào?", "options": ["A) 1954", "B) 1945", "C) 1960", "D) 1975"], "answer": "A"},
{"category": "Lịch sử", "question": "Ai là Tổng thống đầu tiên của Hoa Kỳ?", "options": ["A) George Washington", "B) Abraham Lincoln", "C) John Adams", "D) Thomas Jefferson"], "answer": "A"},
{"category": "Địa lý", "question": "Thủ đô của Nhật Bản là gì?", "options": ["A) Tokyo", "B) Osaka", "C) Kyoto", "D) Nagoya"], "answer": "A"},
{"category": "Địa lý", "question": "Sông nào chảy qua Paris?", "options": ["A) Seine", "B) Thames", "C) Danube", "D) Rhine"], "answer": "A"},
{"category": "Địa lý", "question": "Thành phố nào được mệnh danh là 'Thành phố ngàn hoa' ở Việt Nam?", "options": ["A) Đà Lạt", "B) Huế", "C) Hà Nội", "D) Sapa"], "answer": "A"},
{"category": "Địa lý", "question": "Châu lục nào có diện tích lớn nhất?", "options": ["A) Châu Á", "B) Châu Phi", "C) Châu Mỹ", "D) Châu Âu"], "answer": "A"},
{"category": "Lịch sử", "question": "Ai là người thống nhất đất nước Việt Nam năm 1975?", "options": ["A) Nguyễn Văn Thiệu", "B) Hồ Chí Minh", "C) Lê Duẩn", "D) Võ Nguyên Giáp"], "answer": "B"},
{"category": "Lịch sử", "question": "Triều đại phong kiến cuối cùng của Việt Nam là gì?", "options": ["A) Trần", "B) Lê", "C) Nguyễn", "D) Tây Sơn"], "answer": "C"},
{"category": "Khoa học", "question": "Nguyên tử gồm những hạt cơ bản nào?", "options": ["A) Proton, Neutron, Electron", "B) Electron, Photon, Ion", "C) Proton, Ion, Photon", "D) Neutron, Ion, Proton"], "answer": "A"},
{"category": "Khoa học", "question": "Trái Đất quay quanh Mặt Trời theo quỹ đạo gì?", "options": ["A) Elip", "B) Tròn", "C) Vuông", "D) Dạng sóng"], "answer": "A"},
{"category": "Vật lý", "question": "Vận tốc ánh sáng trong chân không là bao nhiêu?", "options": ["A) 300,000 km/s", "B) 150,000 km/s", "C) 200,000 km/s", "D) 250,000 km/s"], "answer": "A"},
{"category": "Sinh học", "question": "Cơ quan nào đảm nhiệm việc bơm máu đi khắp cơ thể?", "options": ["A) Tim", "B) Gan", "C) Thận", "D) Phổi"], "answer": "A"},
{"category": "Địa lý", "question": "Thủ đô của Thái Lan là gì?", "options": ["A) Bangkok", "B) Chiang Mai", "C) Pattaya", "D) Phuket"], "answer": "A"},
{"category": "Lịch sử", "question": "Chiến thắng Bạch Đằng năm 938 do ai lãnh đạo?", "options": ["A) Ngô Quyền", "B) Trần Hưng Đạo", "C) Lý Thường Kiệt", "D) Lê Hoàn"], "answer": "A"},
{"category": "Văn học", "question": "Ai là tác giả của 'Truyện Kiều'?", "options": ["A) Nguyễn Du", "B) Nguyễn Trãi", "C) Hồ Xuân Hương", "D) Nguyễn Đình Chiểu"], "answer": "A"},
{"category": "Toán học", "question": "Số Pi có giá trị xấp xỉ bằng bao nhiêu?", "options": ["A) 3.12", "B) 3.14", "C) 3.16", "D) 3.18"], "answer": "B"},
{"category": "Khoa học", "question": "Nước sôi ở nhiệt độ bao nhiêu độ C (ở áp suất thường)?", "options": ["A) 90", "B) 95", "C) 100", "D) 105"], "answer": "C"},
{"category": "Địa lý", "question": "Quốc gia nào có dân số đông nhất thế giới?", "options": ["A) Ấn Độ", "B) Trung Quốc", "C) Mỹ", "D) Indonesia"], "answer": "B"},
{"category": "Thiên văn", "question": "Hành tinh nào gần Mặt Trời nhất?", "options": ["A) Sao Thủy", "B) Sao Kim", "C) Trái Đất", "D) Sao Hỏa"], "answer": "A"},
{"category": "Khoa học", "question": "Oxy chiếm khoảng bao nhiêu phần trăm trong không khí?", "options": ["A) 10%", "B) 21%", "C) 30%", "D) 50%"], "answer": "B"},
{"category": "Lịch sử", "question": "Chiếc máy bay đầu tiên được phát minh bởi ai?", "options": ["A) Edison", "B) Wright", "C) Tesla", "D) Bell"], "answer": "B"},
{"category": "Địa lý", "question": "Thủ đô của Úc là gì?", "options": ["A) Sydney", "B) Melbourne", "C) Canberra", "D) Perth"], "answer": "C"},
{"category": "Khoa học", "question": "Hóa chất nào tạo nên vị chua của chanh?", "options": ["A) Axit clohidric", "B) Axit citric", "C) Axit sulfuric", "D) Axit lactic"], "answer": "B"},
{"category": "Vật lý", "question": "Đơn vị đo lực là gì?", "options": ["A) Joule", "B) Newton", "C) Watt", "D) Pascal"], "answer": "B"},
{"category": "Sinh học", "question": "Loài động vật nào được mệnh danh là vua của rừng xanh?", "options": ["A) Sư tử", "B) Hổ", "C) Báo", "D) Voi"], "answer": "A"},
{"category": "Khoa học", "question": "Chất nào chiếm phần lớn trong khí quyển Trái Đất?", "options": ["A) Oxy", "B) Nitơ", "C) Cacbon", "D) Argon"], "answer": "B"},
{"category": "Lịch sử", "question": "Tuyên ngôn Độc lập của Việt Nam được đọc vào ngày nào?", "options": ["A) 30/4/1945", "B) 19/8/1945", "C) 2/9/1945", "D) 10/10/1945"], "answer": "C"},
{"category": "Văn học", "question": "Tác phẩm 'Chí Phèo' do ai viết?", "options": ["A) Nam Cao", "B) Vũ Trọng Phụng", "C) Ngô Tất Tố", "D) Tô Hoài"], "answer": "A"},
{"category": "Địa lý", "question": "Sông Hồng bắt nguồn từ quốc gia nào?", "options": ["A) Việt Nam", "B) Trung Quốc", "C) Lào", "D) Myanmar"], "answer": "B"},
{"category": "Toán học", "question": "Căn bậc hai của 81 là bao nhiêu?", "options": ["A) 8", "B) 9", "C) 10", "D) 11"], "answer": "B"},
{"category": "Sinh học", "question": "Con người có bao nhiêu nhiễm sắc thể?", "options": ["A) 42", "B) 44", "C) 46", "D) 48"], "answer": "C"},
{"category": "Khoa học", "question": "Nguyên tố nào chiếm phần lớn trong nước biển?", "options": ["A) Natri", "B) Canxi", "C) Clo", "D) Kali"], "answer": "A"},
{"category": "Địa lý", "question": "Quốc gia nào có nhiều đảo nhất thế giới?", "options": ["A) Philippines", "B) Indonesia", "C) Na Uy", "D) Thụy Điển"], "answer": "D"},
{"category": "Văn học", "question": "Ai là tác giả của tác phẩm 'Lão Hạc'?", "options": ["A) Nam Cao", "B) Ngô Tất Tố", "C) Nguyễn Công Hoan", "D) Tô Hoài"], "answer": "A"},
{"category": "Vật lý", "question": "Âm thanh truyền nhanh nhất trong môi trường nào?", "options": ["A) Không khí", "B) Nước", "C) Thép", "D) Chân không"], "answer": "C"},
{"category": "Thiên văn", "question": "Mặt Trăng quay quanh hành tinh nào?", "options": ["A) Sao Hỏa", "B) Sao Kim", "C) Trái Đất", "D) Sao Mộc"], "answer": "C"},
{"category": "Địa lý", "question": "Thành phố nào có tháp Eiffel?", "options": ["A) Rome", "B) Berlin", "C) Paris", "D) Madrid"], "answer": "C"},
{"category": "Khoa học", "question": "Công thức hóa học của nước là gì?", "options": ["A) CO2", "B) H2O", "C) O2", "D) H2"], "answer": "B"},
{"category": "Sinh học", "question": "Cơ quan nào giúp con người hô hấp?", "options": ["A) Tim", "B) Phổi", "C) Gan", "D) Thận"], "answer": "B"},
{"category": "Địa lý", "question": "Thủ đô của Hàn Quốc là gì?", "options": ["A) Seoul", "B) Busan", "C) Incheon", "D) Daegu"], "answer": "A"},
{"category": "Khoa học", "question": "Trái Đất có bao nhiêu châu lục?", "options": ["A) 5", "B) 6", "C) 7", "D) 8"], "answer": "C"},
{"category": "Toán học", "question": "Kết quả của 12 x 8 là bao nhiêu?", "options": ["A) 88", "B) 90", "C) 96", "D) 98"], "answer": "C"},
{"category": "Lịch sử", "question": "Ai là người lãnh đạo khởi nghĩa Lam Sơn?", "options": ["A) Trần Hưng Đạo", "B) Lê Lợi", "C) Nguyễn Huệ", "D) Phạm Ngũ Lão"], "answer": "B"},
{"category": "Khoa học", "question": "Nguyên tố nào có ký hiệu là Fe?", "options": ["A) Đồng", "B) Sắt", "C) Kẽm", "D) Chì"], "answer": "B"},
{"category": "Văn học", "question": "Tác phẩm 'Vợ nhặt' là của ai?", "options": ["A) Kim Lân", "B) Nam Cao", "C) Nguyễn Công Hoan", "D) Ngô Tất Tố"], "answer": "A"},
{"category": "Địa lý", "question": "Thủ đô của Lào là gì?", "options": ["A) Viêng Chăn", "B) Luang Prabang", "C) Pakse", "D) Savannakhet"], "answer": "A"},
{"category": "Toán học", "question": "Căn bậc hai của 144 là bao nhiêu?", "options": ["A) 10", "B) 11", "C) 12", "D) 13"], "answer": "C"},
{"category": "Khoa học", "question": "Nguyên tố nào có ký hiệu là O?", "options": ["A) Oxy", "B) Vàng", "C) Hydro", "D) Carbon"], "answer": "A"},
{"category": "Địa lý", "question": "Châu Phi có bao nhiêu quốc gia?", "options": ["A) 48", "B) 50", "C) 54", "D) 60"], "answer": "C"},
{"category": "Lịch sử", "question": "Ai là người phát hiện ra châu Mỹ?", "options": ["A) Marco Polo", "B) Christopher Columbus", "C) Magellan", "D) Vasco da Gama"], "answer": "B"},
{"category": "Văn học", "question": "Tác giả của 'Dế Mèn phiêu lưu ký' là ai?", "options": ["A) Nguyễn Nhật Ánh", "B) Tô Hoài", "C) Nam Cao", "D) Nguyễn Đình Chiểu"], "answer": "B"},
{"category": "Khoa học", "question": "Cơ quan nào của con người chứa não bộ?", "options": ["A) Đầu", "B) Ngực", "C) Bụng", "D) Tay"], "answer": "A"},
{"category": "Địa lý", "question": "Núi Phú Sĩ nằm ở quốc gia nào?", "options": ["A) Hàn Quốc", "B) Trung Quốc", "C) Nhật Bản", "D) Việt Nam"], "answer": "C"},
{"category": "Khoa học", "question": "Tế bào là đơn vị cơ bản của gì?", "options": ["A) Chất rắn", "B) Sinh vật", "C) Năng lượng", "D) Âm thanh"], "answer": "B"},
{"category": "Lịch sử", "question": "Cách mạng tháng Tám ở Việt Nam diễn ra vào năm nào?", "options": ["A) 1930", "B) 1940", "C) 1945", "D) 1954"], "answer": "C"},
{"category": "Địa lý", "question": "Thủ đô của Pháp là gì?", "options": ["A) Berlin", "B) Paris", "C) Rome", "D) London"], "answer": "B"},
{"category": "Toán học", "question": "Tổng của 45 và 55 bằng bao nhiêu?", "options": ["A) 90", "B) 95", "C) 100", "D) 105"], "answer": "C"},
{"category": "Văn học", "question": "Tác phẩm 'Số đỏ' do ai sáng tác?", "options": ["A) Nam Cao", "B) Ngô Tất Tố", "C) Vũ Trọng Phụng", "D) Nguyễn Công Hoan"], "answer": "C"},
{"category": "Khoa học", "question": "Nguyên tố nào có ký hiệu là Au?", "options": ["A) Bạc", "B) Vàng", "C) Sắt", "D) Đồng"], "answer": "B"},
{"category": "Địa lý", "question": "Thủ đô của Campuchia là gì?", "options": ["A) Phnom Penh", "B) Siem Reap", "C) Battambang", "D) Sihanoukville"], "answer": "A"},
{"category": "Sinh học", "question": "Loài động vật có vú nào biết bay?", "options": ["A) Chim cánh cụt", "B) Dơi", "C) Cú mèo", "D) Đại bàng"], "answer": "B"},
{"category": "Lịch sử", "question": "Nhà Trần được thành lập vào năm nào?", "options": ["A) 1225", "B) 1255", "C) 1300", "D) 1350"], "answer": "A"},
{"category": "Khoa học", "question": "Hiện tượng nào làm cầu vồng xuất hiện?", "options": ["A) Khúc xạ ánh sáng", "B) Phản xạ âm thanh", "C) Tán sắc ánh sáng", "D) Nhiễu xạ ánh sáng"], "answer": "C"},
{"category": "Địa lý", "question": "Sông Hàn nằm ở thành phố nào của Việt Nam?", "options": ["A) Huế", "B) Đà Nẵng", "C) Hà Nội", "D) TP Hồ Chí Minh"], "answer": "B"},
{"category": "Toán học", "question": "Kết quả của 15 x 6 là bao nhiêu?", "options": ["A) 80", "B) 85", "C) 90", "D) 95"], "answer": "C"},
{"category": "Khoa học", "question": "Nguyên tố nào cần thiết cho quá trình quang hợp?", "options": ["A) Nitơ", "B) Cacbon", "C) Oxy", "D) CO2"], "answer": "D"},
{"category": "Địa lý", "question": "Nước nào có kim tự tháp cổ đại nổi tiếng?", "options": ["A) Hy Lạp", "B) Ai Cập", "C) Ấn Độ", "D) Iran"], "answer": "B"},
{"category": "Lịch sử", "question": "Ai là người khởi nghĩa Tây Sơn?", "options": ["A) Nguyễn Ánh", "B) Nguyễn Huệ", "C) Trần Hưng Đạo", "D) Lý Thường Kiệt"], "answer": "B"},
{"category": "Sinh học", "question": "Cây xanh hấp thụ khí nào trong quá trình quang hợp?", "options": ["A) Oxy", "B) CO2", "C) Nito", "D) Argon"], "answer": "B"},
{"category": "Khoa học", "question": "Chất nào giúp máu có màu đỏ?", "options": ["A) Hemoglobin", "B) Myosin", "C) Melanin", "D) Keratin"], "answer": "A"},
{"category": "Toán học", "question": "Giá trị của 7² là bao nhiêu?", "options": ["A) 42", "B) 47", "C) 49", "D) 56"], "answer": "C"},
{"category": "Vật lý", "question": "Đơn vị đo công suất là gì?", "options": ["A) Volt", "B) Joule", "C) Watt", "D) Newton"], "answer": "C"},
{"category": "Địa lý", "question": "Thủ đô của Ý là gì?", "options": ["A) Rome", "B) Milan", "C) Venice", "D) Florence"], "answer": "A"},
{"category": "Khoa học", "question": "Công thức hóa học của muối ăn là gì?", "options": ["A) NaOH", "B) NaCl", "C) H2O", "D) CO2"], "answer": "B"},
{"category": "Lịch sử", "question": "Ai là người phát minh ra bóng đèn điện?", "options": ["A) Thomas Edison", "B) Nikola Tesla", "C) Alexander Bell", "D) Albert Einstein"], "answer": "A"},
{"category": "Thiên văn", "question": "Hành tinh lớn nhất trong hệ Mặt Trời là gì?", "options": ["A) Sao Mộc", "B) Sao Thổ", "C) Sao Kim", "D) Sao Thiên Vương"], "answer": "A"},
{"category": "Sinh học", "question": "Bộ phận nào của cây hút nước và chất khoáng?", "options": ["A) Thân", "B) Lá", "C) Rễ", "D) Hoa"], "answer": "C"},
{"category": "Địa lý", "question": "Vịnh Hạ Long thuộc tỉnh nào của Việt Nam?", "options": ["A) Hải Phòng", "B) Quảng Ninh", "C) Thanh Hóa", "D) Nam Định"], "answer": "B"},
{"category": "Khoa học", "question": "Kim loại nào nhẹ nhất?", "options": ["A) Nhôm", "B) Liti", "C) Magie", "D) Sắt"], "answer": "B"},
{"category": "Văn học", "question": "Tác giả của 'Tắt đèn' là ai?", "options": ["A) Nam Cao", "B) Ngô Tất Tố", "C) Vũ Trọng Phụng", "D) Nguyễn Công Hoan"], "answer": "B"},
{"category": "Toán học", "question": "Giá trị của 8³ là bao nhiêu?", "options": ["A) 512", "B) 256", "C) 128", "D) 1024"], "answer": "A"},
{"category": "Khoa học", "question": "Chất nào được gọi là khí nhà kính?", "options": ["A) CO2", "B) O2", "C) H2", "D) N2"], "answer": "A"},
{"category": "Sinh học", "question": "Loài động vật nào đẻ trứng nhưng sống dưới nước?", "options": ["A) Cá", "B) Ếch", "C) Rắn", "D) Cá voi"], "answer": "B"},
{"category": "Địa lý", "question": "Sông Mê Kông chảy qua bao nhiêu quốc gia?", "options": ["A) 4", "B) 5", "C) 6", "D) 7"], "answer": "C"},
{"category": "Khoa học", "question": "Thành phần chính của không khí là gì?", "options": ["A) Oxy", "B) Nitơ", "C) CO2", "D) Heli"], "answer": "B"},
{"category": "Văn học", "question": "Ai là tác giả của 'Nhật ký trong tù'?", "options": ["A) Hồ Chí Minh", "B) Tố Hữu", "C) Xuân Diệu", "D) Nam Cao"], "answer": "A"},
{"category": "Lịch sử", "question": "Năm 1975 ở Việt Nam có sự kiện gì?", "options": ["A) Thống nhất đất nước", "B) Cách mạng tháng Tám", "C) Tuyên ngôn độc lập", "D) Chiến thắng Điện Biên Phủ"], "answer": "A"},
{"category": "Thiên văn", "question": "Hành tinh nào có vòng sao nổi bật?", "options": ["A) Sao Mộc", "B) Sao Thổ", "C) Sao Hỏa", "D) Sao Kim"], "answer": "B"},
{"category": "Địa lý", "question": "Đại dương nào lớn nhất thế giới?", "options": ["A) Đại Tây Dương", "B) Ấn Độ Dương", "C) Thái Bình Dương", "D) Bắc Băng Dương"], "answer": "C"},
{"category": "Văn học", "question": "Tác phẩm 'Chiếc lược ngà' do ai viết?", "options": ["A) Nguyễn Quang Sáng", "B) Tô Hoài", "C) Nam Cao", "D) Ngô Tất Tố"], "answer": "A"},
{"category": "Khoa học", "question": "Đơn vị đo điện áp là gì?", "options": ["A) Ampe", "B) Volt", "C) Ohm", "D) Watt"], "answer": "B"},
{"category": "Sinh học", "question": "Bộ phận nào giúp con người nhìn thấy?", "options": ["A) Tai", "B) Mũi", "C) Mắt", "D) Lưỡi"], "answer": "C"},
{"category": "Khoa học", "question": "Nguyên tố nào có ký hiệu là Fe?", "options": ["A) Bạc", "B) Sắt", "C) Nhôm", "D) Kẽm"], "answer": "B"},
{"category": "Khoa học", "question": "Nguyên tử hiđrô có bao nhiêu proton?", "options": ["A) 0", "B) 1", "C) 2", "D) 3"], "answer": "B"},
{"category": "Khoa học", "question": "Nước sôi ở bao nhiêu độ C (ở áp suất tiêu chuẩn)?", "options": ["A) 50°C", "B) 75°C", "C) 100°C", "D) 125°C"], "answer": "C"},
{"category": "Khoa học", "question": "Tốc độ ánh sáng trong chân không là bao nhiêu?", "options": ["A) 3×10⁵ m/s", "B) 3×10⁶ m/s", "C) 3×10⁷ m/s", "D) 3×10⁸ m/s"], "answer": "D"},
{"category": "Khoa học", "question": "Ai là người phát minh ra bóng đèn điện?", "options": ["A) Albert Einstein", "B) Isaac Newton", "C) Thomas Edison", "D) Nikola Tesla"], "answer": "C"},
{"category": "Khoa học", "question": "Thực vật hấp thụ khí nào để quang hợp?", "options": ["A) O₂", "B) N₂", "C) CO₂", "D) H₂"], "answer": "C"},
{"category": "Khoa học", "question": "Trái Đất quay quanh Mặt Trời mất bao lâu?", "options": ["A) 24 giờ", "B) 1 tháng", "C) 1 năm", "D) 10 năm"], "answer": "C"},
{"category": "Khoa học", "question": "Chất nào trong máu giúp vận chuyển oxy?", "options": ["A) Hemoglobin", "B) Glucose", "C) Insulin", "D) Enzyme"], "answer": "A"},
{"category": "Khoa học", "question": "Nguyên tố nào chiếm tỷ lệ lớn nhất trong không khí?", "options": ["A) Oxy", "B) Nitơ", "C) CO₂", "D) Argon"], "answer": "B"},
{"category": "Khoa học", "question": "Dòng điện được đo bằng đơn vị nào?", "options": ["A) Volt", "B) Watt", "C) Ampere", "D) Ohm"], "answer": "C"},
{"category": "Khoa học", "question": "Động vật nào có thể bay lùi?", "options": ["A) Chim én", "B) Ong", "C) Chuồn chuồn", "D) Chim ruồi"], "answer": "D"},
{"category": "Khoa học", "question": "Lớp ngoài cùng của Trái Đất được gọi là gì?", "options": ["A) Manti", "B) Lõi", "C) Vỏ Trái Đất", "D) Thạch quyển"], "answer": "C"},
{"category": "Khoa học", "question": "Chất nào là dung môi phổ biến nhất trên Trái Đất?", "options": ["A) Cồn", "B) Dầu", "C) Nước", "D) Axit"], "answer": "C"},
{"category": "Khoa học", "question": "Cơ quan nào trong cơ thể người sản xuất insulin?", "options": ["A) Gan", "B) Thận", "C) Tuyến tụy", "D) Tim"], "answer": "C"},
{"category": "Khoa học", "question": "Âm thanh không thể truyền trong môi trường nào?", "options": ["A) Nước", "B) Rắn", "C) Không khí", "D) Chân không"], "answer": "D"},
{"category": "Khoa học", "question": "Kim loại nào có tính dẫn điện tốt nhất?", "options": ["A) Đồng", "B) Bạc", "C) Vàng", "D) Nhôm"], "answer": "B"},
{"category": "Khoa học", "question": "Đơn vị đo năng lượng trong hệ SI là gì?", "options": ["A) Pascal", "B) Joule", "C) Newton", "D) Watt"], "answer": "B"},
{"category": "Khoa học", "question": "Hành tinh nào gần Mặt Trời nhất?", "options": ["A) Sao Kim", "B) Sao Thủy", "C) Sao Hỏa", "D) Sao Mộc"], "answer": "B"},
{"category": "Khoa học", "question": "Loài nào được xem là động vật có vú lớn nhất trên Trái Đất?", "options": ["A) Cá voi xanh", "B) Voi châu Phi", "C) Cá mập voi", "D) Hà mã"], "answer": "A"},
{"category": "Khoa học", "question": "Cái gì giữ cho các hành tinh quay quanh Mặt Trời?", "options": ["A) Lực hấp dẫn", "B) Lực đẩy", "C) Từ trường", "D) Sóng âm"], "answer": "A"},
{"category": "Địa lý", "question": "Quốc gia nào có dân số lớn nhất thế giới tính đến năm 2025?", "options": ["A) Ấn Độ", "B) Trung Quốc", "C) Mỹ", "D) Indonesia"], "answer": "A"},
{"category": "Địa lý", "question": "Dãy núi Andes nằm trên châu lục nào?", "options": ["A) Bắc Mỹ", "B) Nam Mỹ", "C) Châu Á", "D) Châu Âu"], "answer": "B"},
{"category": "Địa lý", "question": "Sa mạc Atacama nằm ở quốc gia nào?", "options": ["A) Chile", "B) Peru", "C) Argentina", "D) Bolivia"], "answer": "A"},
{"category": "Địa lý", "question": "Sông Dương Tử chảy qua bao nhiêu quốc gia?", "options": ["A) 1", "B) 2", "C) 3", "D) 4"], "answer": "A"},
{"category": "Lịch sử", "question": "Cuộc Cách mạng Công nghiệp bắt đầu ở đâu?", "options": ["A) Pháp", "B) Mỹ", "C) Anh", "D) Đức"], "answer": "C"},
{"category": "Lịch sử", "question": "Tuyên ngôn Độc lập Hoa Kỳ được ký vào ngày nào?", "options": ["A) 4/7/1776", "B) 1/1/1775", "C) 14/7/1776", "D) 15/8/1777"], "answer": "A"},
{"category": "Lịch sử", "question": "Chiến tranh Lạnh là xung đột giữa hai khối quốc gia nào?", "options": ["A) Mỹ và Trung Quốc", "B) Liên Xô và Mỹ", "C) Anh và Đức", "D) Nhật và Mỹ"], "answer": "B"},
{"category": "Lịch sử", "question": "Ai là người chỉ huy quân đội Hy Lạp trong cuộc chiến chống Ba Tư?", "options": ["A) Pericles", "B) Alexander Đại đế", "C) Leonidas", "D) Socrates"], "answer": "C"},
{"category": "Văn học", "question": "Tác phẩm 'Những người khốn khổ' là của ai?", "options": ["A) Victor Hugo", "B) Balzac", "C) Tolstoy", "D) Dostoievsky"], "answer": "A"},
{"category": "Văn học", "question": "Tác giả 'Tắt đèn' là ai?", "options": ["A) Nam Cao", "B) Ngô Tất Tố", "C) Vũ Trọng Phụng", "D) Tô Hoài"], "answer": "B"},
{"category": "Văn học", "question": "Nhân vật Romeo thuộc tác phẩm nào?", "options": ["A) Hamlet", "B) Macbeth", "C) Othello", "D) Romeo và Juliet"], "answer": "D"},
{"category": "Văn học", "question": "Thơ Haiku có nguồn gốc từ quốc gia nào?", "options": ["A) Trung Quốc", "B) Nhật Bản", "C) Hàn Quốc", "D) Việt Nam"], "answer": "B"},
{"category": "Toán học", "question": "Giải phương trình: 2x + 5 = 11. Giá trị của x là gì?", "options": ["A) 2", "B) 3", "C) 4", "D) 5"], "answer": "C"},
{"category": "Toán học", "question": "Tổng của các góc trong một tam giác là bao nhiêu độ?", "options": ["A) 90°", "B) 120°", "C) 180°", "D) 360°"], "answer": "C"},
{"category": "Toán học", "question": "Đạo hàm của sin(x) là gì?", "options": ["A) cos(x)", "B) -cos(x)", "C) -sin(x)", "D) tan(x)"], "answer": "A"},
{"category": "Toán học", "question": "Số nguyên tố nhỏ nhất là gì?", "options": ["A) 0", "B) 1", "C) 2", "D) 3"], "answer": "C"},
{"category": "Khoa học", "question": "Ai là người phát hiện ra định luật vạn vật hấp dẫn?", "options": ["A) Galileo", "B) Newton", "C) Einstein", "D) Faraday"], "answer": "B"},
{"category": "Khoa học", "question": "Nguyên tố nào có ký hiệu là O?", "options": ["A) Oxy", "B) Osmium", "C) Oganesson", "D) Oxalat"], "answer": "A"},
{"category": "Khoa học", "question": "Hành tinh nào có vòng bao quanh nổi bật nhất?", "options": ["A) Sao Mộc", "B) Sao Thổ", "C) Sao Thiên Vương", "D) Sao Hải Vương"], "answer": "B"},
{"category": "Khoa học", "question": "Máu người có màu đỏ do chứa chất gì?", "options": ["A) Hemoglobin", "B) Myoglobin", "C) Plasma", "D) Oxy"], "answer": "A"},
{"category": "Công nghệ", "question": "AI là viết tắt của cụm từ nào?", "options": ["A) Artificial Intelligence", "B) Automated Interface", "C) Advanced Internet", "D) Applied Information"], "answer": "A"},
{"category": "Công nghệ", "question": "Ngôn ngữ lập trình nào được dùng chủ yếu trong trí tuệ nhân tạo?", "options": ["A) Python", "B) PHP", "C) C#", "D) Ruby"], "answer": "A"},
{"category": "Công nghệ", "question": "Blockchain được ứng dụng phổ biến trong lĩnh vực nào?", "options": ["A) Mạng xã hội", "B) Tiền điện tử", "C) Giải trí", "D) Giao thông"], "answer": "B"},
{"category": "Công nghệ", "question": "CPU là viết tắt của cụm từ nào?", "options": ["A) Central Processing Unit", "B) Computer Power Unit", "C) Control Program Unit", "D) Core Processing Utility"], "answer": "A"},
{"category": "Thể thao", "question": "Cầu thủ nào giành Quả bóng vàng năm 2023?", "options": ["A) Haaland", "B) Messi", "C) Mbappé", "D) Ronaldo"], "answer": "B"},
{"category": "Thể thao", "question": "Môn thể thao nào được mệnh danh là 'Vua của các môn thể thao'?", "options": ["A) Bóng rổ", "B) Bóng đá", "C) Quần vợt", "D) Điền kinh"], "answer": "B"},
{"category": "Thể thao", "question": "Trong bóng rổ, mỗi đội có bao nhiêu người trên sân?", "options": ["A) 4", "B) 5", "C) 6", "D) 7"], "answer": "B"},
{"category": "Thể thao", "question": "Giải đấu bóng đá lớn nhất hành tinh là gì?", "options": ["A) Euro", "B) Copa America", "C) World Cup", "D) Champions League"], "answer": "C"},
{"category": "Vật lý", "question": "Đơn vị đo lực là gì?", "options": ["A) Watt", "B) Pascal", "C) Newton", "D) Joule"], "answer": "C"},
{"category": "Vật lý", "question": "Ánh sáng là dạng nào của năng lượng?", "options": ["A) Hóa năng", "B) Nhiệt năng", "C) Điện năng", "D) Bức xạ điện từ"], "answer": "D"},
{"category": "Vật lý", "question": "Công thức tính vận tốc là gì?", "options": ["A) v = s/t", "B) v = t/s", "C) v = s×t", "D) v = s²/t"], "answer": "A"},
{"category": "Sinh học", "question": "Động vật nào có thể tự phát sáng?", "options": ["A) Sứa", "B) Cá mập", "C) Cá heo", "D) Bạch tuộc"], "answer": "A"},
{"category": "Sinh học", "question": "Cấu trúc nào chứa thông tin di truyền của sinh vật?", "options": ["A) RNA", "B) ADN", "C) Protein", "D) Enzyme"], "answer": "B"},
{"category": "Triết học", "question": "Ai là người sáng lập chủ nghĩa duy vật biện chứng?", "options": ["A) Hegel", "B) Marx và Engels", "C) Kant", "D) Aristotle"], "answer": "B"},
{"category": "Triết học", "question": "Khái niệm 'bản thể học' nghiên cứu về điều gì?", "options": ["A) Tri thức", "B) Sự tồn tại", "C) Đạo đức", "D) Cảm xúc"], "answer": "B"},
{"category": "Kinh tế", "question": "GDP là viết tắt của cụm từ nào?", "options": ["A) Global Development Plan", "B) Gross Domestic Product", "C) General Data Policy", "D) Government Debt Payment"], "answer": "B"},
{"category": "Kinh tế", "question": "Thị trường chứng khoán đầu tiên trên thế giới được thành lập ở đâu?", "options": ["A) Mỹ", "B) Hà Lan", "C) Anh", "D) Pháp"], "answer": "B"},
{"category": "Địa chính trị", "question": "Tổ chức NATO được thành lập năm nào?", "options": ["A) 1945", "B) 1947", "C) 1949", "D) 1950"], "answer": "C"},
{"category": "Địa chính trị", "question": "Liên Hợp Quốc có trụ sở chính đặt ở đâu?", "options": ["A) Paris", "B) London", "C) Geneva", "D) New York"], "answer": "D"},
{"category": "Công nghệ", "question": "Ai được coi là cha đẻ của máy tính hiện đại?", "options": ["A) Alan Turing", "B) Bill Gates", "C) Steve Jobs", "D) Charles Babbage"], "answer": "D"},
{"category": "Công nghệ", "question": "Ngôn ngữ lập trình nào được sử dụng để phát triển trình duyệt Chrome?", "options": ["A) C++", "B) Python", "C) Java", "D) Rust"], "answer": "A"},
{"category": "Công nghệ", "question": "AI là viết tắt của từ gì?", "options": ["A) Advanced Internet", "B) Artificial Intelligence", "C) Automated Input", "D) Adaptive Interface"], "answer": "B"},
{"category": "Công nghệ", "question": "Hệ điều hành Android thuộc sở hữu của công ty nào?", "options": ["A) Apple", "B) Google", "C) Microsoft", "D) Samsung"], "answer": "B"},
{"category": "Công nghệ", "question": "RAM là viết tắt của gì?", "options": ["A) Read Always Memory", "B) Random Access Memory", "C) Rapid Action Memory", "D) Run Active Mode"], "answer": "B"},
{"category": "Khoa học", "question": "Nguyên tố nào có ký hiệu hóa học là O?", "options": ["A) Oxi", "B) Vàng", "C) Bạc", "D) Sắt"], "answer": "A"},
{"category": "Khoa học", "question": "Trái Đất quay quanh Mặt Trời theo quỹ đạo gì?", "options": ["A) Tròn", "B) Elip", "C) Vuông", "D) Hình sin"], "answer": "B"},
{"category": "Khoa học", "question": "Ai phát hiện ra định luật vạn vật hấp dẫn?", "options": ["A) Einstein", "B) Newton", "C) Galileo", "D) Kepler"], "answer": "B"},
{"category": "Khoa học", "question": "Máu người có bao nhiêu nhóm chính?", "options": ["A) 2", "B) 3", "C) 4", "D) 5"], "answer": "C"},
{"category": "Khoa học", "question": "Ánh sáng truyền đi nhanh nhất trong môi trường nào?", "options": ["A) Không khí", "B) Nước", "C) Chân không", "D) Thủy tinh"], "answer": "C"},
{"category": "Âm nhạc", "question": "Ai là người sáng tác bản giao hưởng 'Vận mệnh' (Symphony No.5)?", "options": ["A) Beethoven", "B) Mozart", "C) Bach", "D) Tchaikovsky"], "answer": "A"},
{"category": "Âm nhạc", "question": "Nhạc cụ nào có 88 phím?", "options": ["A) Guitar", "B) Piano", "C) Violin", "D) Trống"], "answer": "B"},
{"category": "Âm nhạc", "question": "Thể loại nhạc 'hip hop' bắt nguồn từ quốc gia nào?", "options": ["A) Anh", "B) Mỹ", "C) Pháp", "D) Brazil"], "answer": "B"},
{"category": "Âm nhạc", "question": "Ca sĩ nào được mệnh danh là 'Ông hoàng nhạc Pop'?", "options": ["A) Elvis Presley", "B) Michael Jackson", "C) Freddie Mercury", "D) Justin Bieber"], "answer": "B"},
{"category": "Âm nhạc", "question": "Dàn nhạc giao hưởng thường chia thành mấy nhóm nhạc cụ chính?", "options": ["A) 2", "B) 3", "C) 4", "D) 5"], "answer": "C"},
{"category": "Thể thao", "question": "Một trận bóng đá có bao nhiêu cầu thủ trên sân (tổng 2 đội)?", "options": ["A) 20", "B) 22", "C) 24", "D) 26"], "answer": "B"},
{"category": "Thể thao", "question": "Huyền thoại bóng rổ Michael Jordan thi đấu cho đội nào?", "options": ["A) Lakers", "B) Bulls", "C) Celtics", "D) Heat"], "answer": "B"},
{"category": "Thể thao", "question": "Sân tennis được chia làm mấy loại chính theo chất liệu?", "options": ["A) 2", "B) 3", "C) 4", "D) 5"], "answer": "B"},
{"category": "Thể thao", "question": "Giải bóng đá Euro tổ chức mấy năm một lần?", "options": ["A) 2", "B) 3", "C) 4", "D) 5"], "answer": "C"},
{"category": "Thể thao", "question": "Môn thể thao nào sử dụng gậy và bóng nhỏ trên sân cỏ rộng?", "options": ["A) Golf", "B) Bóng chày", "C) Bóng gậy", "D) Polo"], "answer": "A"},
{"category": "Xã hội", "question": "Liên Hợp Quốc (UN) được thành lập năm nào?", "options": ["A) 1919", "B) 1945", "C) 1950", "D) 1961"], "answer": "B"},
{"category": "Xã hội", "question": "Ngày Quốc tế Lao động là ngày nào?", "options": ["A) 1/1", "B) 1/5", "C) 2/9", "D) 20/11"], "answer": "B"},
{"category": "Xã hội", "question": "Tổ chức WHO chuyên về lĩnh vực gì?", "options": ["A) Kinh tế", "B) Y tế", "C) Giáo dục", "D) Môi trường"], "answer": "B"},
{"category": "Xã hội", "question": "Hiến pháp là gì?", "options": ["A) Luật của tôn giáo", "B) Luật cơ bản của một quốc gia", "C) Quy tắc đạo đức", "D) Bộ luật thương mại"], "answer": "B"},
{"category": "Xã hội", "question": "Tiền tệ của Nhật Bản là gì?", "options": ["A) Won", "B) Ringgit", "C) Yên", "D) Nhân dân tệ"], "answer": "C"},
{"category": "Logic", "question": "Nếu tất cả mèo đều có lông và Tom là mèo, thì Tom có lông không?", "options": ["A) Có", "B) Không", "C) Có thể có", "D) Không biết"], "answer": "A"},
{"category": "Logic", "question": "Nếu hôm nay là thứ Ba, thì sau 3 ngày nữa là thứ mấy?", "options": ["A) Thứ Năm", "B) Thứ Sáu", "C) Thứ Bảy", "D) Chủ Nhật"], "answer": "C"},
{"category": "Logic", "question": "5 người xếp hàng. Nếu A đứng trước B và B đứng trước C, thì ai đứng sau C?", "options": ["A) D", "B) A", "C) B", "D) Không biết"], "answer": "A"},
{"category": "Logic", "question": "Nếu 2 con vịt đi trước 1 con vịt và 2 con vịt đi sau 1 con vịt, tổng cộng có bao nhiêu con vịt?", "options": ["A) 3", "B) 4", "C) 5", "D) 6"], "answer": "A"},
{"category": "Logic", "question": "Nếu 1 giờ có 60 phút, 3/4 giờ là bao nhiêu phút?", "options": ["A) 30", "B) 45", "C) 50", "D) 40"], "answer": "B"},
{"category": "Lịch sử", "question": "Chiến tranh lạnh diễn ra giữa hai khối nào?", "options": ["A) NATO và Liên Xô", "B) Mỹ và Trung Quốc", "C) Anh và Đức", "D) Nhật và Hàn"], "answer": "A"},
{"category": "Lịch sử", "question": "Ai là người viết bản 'Tuyên ngôn độc lập' của Việt Nam năm 1945?", "options": ["A) Phạm Văn Đồng", "B) Võ Nguyên Giáp", "C) Hồ Chí Minh", "D) Trường Chinh"], "answer": "C"},
{"category": "Lịch sử", "question": "Cách mạng công nghiệp lần thứ nhất bắt đầu ở đâu?", "options": ["A) Mỹ", "B) Pháp", "C) Anh", "D) Đức"], "answer": "C"},
{"category": "Lịch sử", "question": "Vạn Lý Trường Thành được xây dựng chủ yếu để chống ai?", "options": ["A) Nhật Bản", "B) Hung Nô", "C) Mông Cổ", "D) Tây Tạng"], "answer": "B"},
{"category": "Lịch sử", "question": "Trận Waterloo năm 1815 đánh dấu sự thất bại của ai?", "options": ["A) Napoleon", "B) Caesar", "C) Alexander Đại đế", "D) Hitler"], "answer": "A"},
{"category": "Khoa học", "question": "Nguyên tử gồm có bao nhiêu loại hạt cơ bản?", "options": ["A) 2", "B) 3", "C) 4", "D) 5"], "answer": "B"},
{"category": "Khoa học", "question": "Tốc độ ánh sáng trong chân không xấp xỉ bao nhiêu km/s?", "options": ["A) 100,000", "B) 200,000", "C) 300,000", "D) 400,000"], "answer": "C"},
{"category": "Khoa học", "question": "Người đầu tiên đặt chân lên Mặt Trăng là ai?", "options": ["A) Neil Armstrong", "B) Buzz Aldrin", "C) Yuri Gagarin", "D) Alan Shepard"], "answer": "A"},
{"category": "Khoa học", "question": "Cơ quan nào trong cơ thể người chịu trách nhiệm lọc máu?", "options": ["A) Tim", "B) Gan", "C) Thận", "D) Phổi"], "answer": "C"},
{"category": "Khoa học", "question": "Khí nào chiếm tỷ lệ lớn nhất trong khí quyển Trái Đất?", "options": ["A) Oxi", "B) Nitơ", "C) CO₂", "D) Argon"], "answer": "B"},
{"category": "Triết học", "question": "Ai là tác giả của tác phẩm 'Cộng sản tuyên ngôn'?", "options": ["A) Lenin", "B) Marx và Engels", "C) Stalin", "D) Rousseau"], "answer": "B"},
{"category": "Triết học", "question": "Tư tưởng 'Tôi tư duy, nên tôi tồn tại' là của ai?", "options": ["A) Kant", "B) Descartes", "C) Plato", "D) Socrates"], "answer": "B"},
{"category": "Triết học", "question": "Học thuyết 'Âm Dương - Ngũ Hành' thuộc nền triết học nào?", "options": ["A) Hy Lạp", "B) Trung Hoa", "C) Ấn Độ", "D) Ai Cập"], "answer": "B"},
{"category": "Triết học", "question": "Theo triết học Marx-Lenin, vật chất là gì?", "options": ["A) Cái có khối lượng", "B) Cái tồn tại khách quan ngoài ý thức", "C) Cái do con người tạo ra", "D) Cái có năng lượng"], "answer": "B"},
{"category": "Triết học", "question": "Ai là người sáng lập chủ nghĩa hiện sinh?", "options": ["A) Sartre", "B) Hegel", "C) Nietzsche", "D) Kierkegaard"], "answer": "D"},
{"category": "Địa lý", "question": "Lục địa nào có diện tích nhỏ nhất thế giới?", "options": ["A) Châu Âu", "B) Châu Đại Dương", "C) Châu Nam Cực", "D) Châu Phi"], "answer": "B"},
{"category": "Địa lý", "question": "Sông Mê Kông chảy qua bao nhiêu quốc gia?", "options": ["A) 4", "B) 5", "C) 6", "D) 7"], "answer": "C"},
{"category": "Địa lý", "question": "Quốc gia nào nằm trên cả hai châu lục Á và Âu?", "options": ["A) Nga", "B) Thổ Nhĩ Kỳ", "C) Kazakhstan", "D) Cả 3 đáp án trên"], "answer": "D"},
{"category": "Địa lý", "question": "Vùng đất thấp nhất trên Trái Đất là gì?", "options": ["A) Thung lũng Chết", "B) Biển Chết", "C) Grand Canyon", "D) Hồ Baikal"], "answer": "B"},
{"category": "Địa lý", "question": "Sa mạc Atacama nằm ở châu lục nào?", "options": ["A) Châu Phi", "B) Châu Nam Mỹ", "C) Châu Á", "D) Châu Đại Dương"], "answer": "B"},
{"category": "Văn học", "question": "Tác phẩm 'Truyện Kiều' của Nguyễn Du gồm bao nhiêu câu thơ?", "options": ["A) 2548", "B) 3246", "C) 3254", "D) 3456"], "answer": "C"},
{"category": "Văn học", "question": "Ai là tác giả của 'Nhật ký trong tù'?", "options": ["A) Tố Hữu", "B) Hồ Chí Minh", "C) Xuân Diệu", "D) Nam Cao"], "answer": "B"},
{"category": "Văn học", "question": "Tác phẩm 'Romeo và Juliet' thuộc thể loại gì?", "options": ["A) Tiểu thuyết", "B) Truyện ngắn", "C) Bi kịch", "D) Anh hùng ca"], "answer": "C"},
{"category": "Văn học", "question": "Tác giả của 'Chiếc lược ngà' là ai?", "options": ["A) Nguyễn Minh Châu", "B) Nguyễn Quang Sáng", "C) Nam Cao", "D) Kim Lân"], "answer": "B"},
{"category": "Văn học", "question": "Nhân vật Chí Phèo xuất hiện trong tác phẩm nào?", "options": ["A) Số đỏ", "B) Lão Hạc", "C) Chí Phèo", "D) Đời thừa"], "answer": "C"},
{"category": "Logic", "question": "Nếu tất cả học sinh đều thích toán, An là học sinh, An có thích toán không?", "options": ["A) Có", "B) Không", "C) Không chắc", "D) Có thể"], "answer": "A"},
{"category": "Logic", "question": "Một con mèo và nửa con mèo bắt 1 con chuột rưỡi trong 1 phút rưỡi. Hỏi 9 con mèo bắt được bao nhiêu chuột trong 9 phút?", "options": ["A) 27", "B) 54", "C) 81", "D) 108"], "answer": "B"},
{"category": "Logic", "question": "Có 5 cây nến đang cháy, gió thổi tắt 2 cây. Hỏi còn lại bao nhiêu cây nến?", "options": ["A) 3", "B) 2", "C) 5", "D) 7"], "answer": "C"},
{"category": "Logic", "question": "Một người đi bộ 3km/h, người kia đi xe đạp 9km/h. Nếu họ xuất phát cùng lúc từ hai điểm cách nhau 12km, họ gặp nhau sau bao lâu?", "options": ["A) 1h", "B) 1.5h", "C) 2h", "D) 3h"], "answer": "B"},
{"category": "Logic", "question": "Nếu 2 + 2 = 4, 3 + 3 = 6, thì 4 + 4 bằng bao nhiêu?", "options": ["A) 6", "B) 7", "C) 8", "D) 9"], "answer": "C"},
{"category": "Toán học", "question": "Giải phương trình: 3x - 7 = 11. Giá trị x là?", "options": ["A) 4", "B) 5", "C) 6", "D) 7"], "answer": "C"},
{"category": "Toán học", "question": "Tích của 7 và 8 bằng bao nhiêu?", "options": ["A) 54", "B) 56", "C) 58", "D) 64"], "answer": "B"},
{"category": "Toán học", "question": "Số nguyên tố nhỏ hơn 10 là số nào?", "options": ["A) 1, 2, 3, 5, 7", "B) 2, 3, 5, 7", "C) 1, 3, 5, 7, 9", "D) 2, 3, 5, 7, 9"], "answer": "B"},
{"category": "Toán học", "question": "Diện tích hình chữ nhật = chiều dài × chiều rộng. Hình chữ nhật có chiều dài 8m, rộng 5m, diện tích là?", "options": ["A) 35 m²", "B) 40 m²", "C) 45 m²", "D) 50 m²"], "answer": "B"},
{"category": "Toán học", "question": "Nghiệm của phương trình x² - 9 = 0 là?", "options": ["A) 3", "B) -3", "C) ±3", "D) 0"], "answer": "C"},
{"category": "Lập trình", "question": "Ngôn ngữ nào được sử dụng phổ biến nhất cho AI?", "options": ["A) Python", "B) Java", "C) C++", "D) Ruby"], "answer": "A"},
{"category": "Lập trình", "question": "HTML là viết tắt của gì?", "options": ["A) Hyper Text Markup Language", "B) Hyperlink Text Manual Language", "C) High Text Markup Logic", "D) Hyper Transfer Markdown Language"], "answer": "A"},
{"category": "Lập trình", "question": "Python sử dụng dấu gì để kết thúc câu lệnh?", "options": ["A) ;", "B) :", "C) Không cần", "D) ."], "answer": "C"},
{"category": "Lập trình", "question": "Hàm trong lập trình dùng để làm gì?", "options": ["A) Lưu dữ liệu", "B) Thực hiện một tác vụ cụ thể", "C) Kết nối mạng", "D) Hiển thị giao diện"], "answer": "B"},
{"category": "Lập trình", "question": "Cú pháp 'for i in range(5):' trong Python lặp bao nhiêu lần?", "options": ["A) 4", "B) 5", "C) 6", "D) 0"], "answer": "B"},
{"category": "Vật lý", "question": "Công thức tính áp suất là?", "options": ["A) P = F/A", "B) P = m*v", "C) P = E/t", "D) P = V/I"], "answer": "A"},
{"category": "Vật lý", "question": "Đơn vị đo năng lượng là gì?", "options": ["A) Newton", "B) Watt", "C) Joule", "D) Pascal"], "answer": "C"},
{"category": "Vật lý", "question": "Sóng điện từ truyền trong chân không với tốc độ bao nhiêu?", "options": ["A) 3×10^5 km/s", "B) 3×10^8 m/s", "C) 3×10^6 m/s", "D) 3×10^9 km/s"], "answer": "B"},
{"category": "Vật lý", "question": "Hiện tượng gương phản chiếu ánh sáng là gì?", "options": ["A) Khúc xạ", "B) Phản xạ", "C) Tán xạ", "D) Nhiễu xạ"], "answer": "B"},
{"category": "Vật lý", "question": "Đơn vị đo điện trở là gì?", "options": ["A) Ohm", "B) Volt", "C) Ampere", "D) Watt"], "answer": "A"},
{"category": "Triết học", "question": "Ai là tác giả của 'Phê phán lý trí thuần túy'?", "options": ["A) Hegel", "B) Kant", "C) Descartes", "D) Aristotle"], "answer": "B"},
{"category": "Triết học", "question": "Chủ nghĩa hiện sinh nhấn mạnh điều gì?", "options": ["A) Giáo lý tôn giáo", "B) Tự do và trách nhiệm cá nhân", "C) Vật chất", "D) Chính trị"], "answer": "B"},
{"category": "Triết học", "question": "Ai là người phát triển học thuyết duy vật biện chứng?", "options": ["A) Marx và Engels", "B) Hegel", "C) Kant", "D) Plato"], "answer": "A"},
{"category": "Triết học", "question": "Khái niệm 'bản thể học' nghiên cứu về?", "options": ["A) Tri thức", "B) Sự tồn tại", "C) Cảm xúc", "D) Đạo đức"], "answer": "B"},
{"category": "Triết học", "question": "Tư tưởng 'Tôi tư duy, nên tôi tồn tại' thuộc ai?", "options": ["A) Descartes", "B) Kant", "C) Aristotle", "D) Socrates"], "answer": "A"},
{"category": "Logic IQ", "question": "Nếu 5 máy in in 5 tờ trong 5 phút, 100 máy in in 100 tờ trong bao lâu?", "options": ["A) 5 phút", "B) 100 phút", "C) 20 phút", "D) 10 phút"], "answer": "A"},
{"category": "Logic IQ", "question": "Nếu hôm nay là thứ Năm, 2 ngày sau là thứ mấy?", "options": ["A) Thứ Sáu", "B) Thứ Bảy", "C) Chủ Nhật", "D) Thứ Hai"], "answer": "B"},
{"category": "Logic IQ", "question": "Có 3 hộp: 1 chứa táo, 1 chứa cam, 1 chứa táo và cam. Mọi hộp đều dán nhãn sai. Bạn mở 1 hộp, lấy 1 trái. Làm sao để dán đúng nhãn?", "options": ["A) Mở hộp bất kỳ", "B) Mở hộp nhãn táo & cam", "C) Mở hộp nhãn táo", "D) Không thể"], "answer": "B"},
{"category": "Logic IQ", "question": "Nếu 2 + 2 = 4, 2×2 = 4, thì 2² + 2² = ?", "options": ["A) 4", "B) 6", "C) 8", "D) 16"], "answer": "C"},
{"category": "Logic IQ", "question": "Một đồng hồ chạy nhanh 5 phút mỗi giờ. Nếu bây giờ đúng 12h, 3 giờ sau đồng hồ chỉ mấy giờ?", "options": ["A) 2:00", "B) 3:15", "C) 3:10", "D) 3:05"], "answer": "B"},
{"category": "Lịch sử thế giới", "question": "Ai là thủ tướng Anh trong Thế chiến II?", "options": ["A) Winston Churchill", "B) Neville Chamberlain", "C) Margaret Thatcher", "D) Tony Blair"], "answer": "A"},
{"category": "Lịch sử thế giới", "question": "Chiến tranh thế giới thứ nhất bắt đầu năm nào?", "options": ["A) 1912", "B) 1914", "C) 1918", "D) 1920"], "answer": "B"},
{"category": "Lịch sử thế giới", "question": "Cuộc cách mạng Pháp bắt đầu năm nào?", "options": ["A) 1776", "B) 1789", "C) 1799", "D) 1804"], "answer": "B"},
{"category": "Lịch sử thế giới", "question": "Ai là lãnh đạo Liên Xô trong Chiến tranh Lạnh?", "options": ["A) Stalin", "B) Lenin", "C) Gorbachev", "D) Khrushchev"], "answer": "C"},
{"category": "Lịch sử thế giới", "question": "Nobel Hòa bình đầu tiên được trao năm nào?", "options": ["A) 1895", "B) 1901", "C) 1910", "D) 1920"], "answer": "B"},
{"category": "Toán học", "question": "Nếu f(x) = 2x + 3, giá trị của f(5) là?", "options": ["A) 10", "B) 11", "C) 13", "D) 15"], "answer": "C"},
{"category": "Toán học", "question": "Số ngẫu nhiên chọn từ 1 đến 10, xác suất chọn số chẵn là bao nhiêu?", "options": ["A) 1/2", "B) 1/3", "C) 2/5", "D) 3/5"], "answer": "A"},
{"category": "Toán học", "question": "Diện tích hình tam giác có đáy 8cm, cao 5cm là?", "options": ["A) 20 cm²", "B) 40 cm²", "C) 30 cm²", "D) 25 cm²"], "answer": "A"},
{"category": "Toán học", "question": "Tổng các số từ 1 đến 100 là?", "options": ["A) 5050", "B) 5000", "C) 5100", "D) 5005"], "answer": "A"},
{"category": "Toán học", "question": "Giá trị của π xấp xỉ bao nhiêu?", "options": ["A) 3.12", "B) 3.14", "C) 3.16", "D) 3.18"], "answer": "B"},
{"category": "Vật lý", "question": "Định luật vạn vật hấp dẫn do ai phát hiện?", "options": ["A) Galileo", "B) Newton", "C) Einstein", "D) Kepler"], "answer": "B"},
{"category": "Vật lý", "question": "Hạt nào mang điện âm?", "options": ["A) Proton", "B) Neutron", "C) Electron", "D) Positron"], "answer": "C"},
{"category": "Vật lý", "question": "Đơn vị đo điện tích là gì?", "options": ["A) Coulomb", "B) Ampere", "C) Volt", "D) Watt"], "answer": "A"},
{"category": "Vật lý", "question": "Hiệu ứng nào chứng minh ánh sáng vừa là sóng vừa là hạt?", "options": ["A) Doppler", "B) Photoelectric", "C) Khúc xạ", "D) Gương phản chiếu"], "answer": "B"},
{"category": "Vật lý", "question": "Đơn vị đo tần số là gì?", "options": ["A) Hertz", "B) Newton", "C) Pascal", "D) Joule"], "answer": "A"},
{"category": "Lập trình", "question": "Trong Python, 'len([1,2,3])' trả về giá trị gì?", "options": ["A) 2", "B) 3", "C) 1", "D) Error"], "answer": "B"},
{"category": "Lập trình", "question": "Cú pháp tạo vòng lặp for trong Python chuẩn là?", "options": ["A) for i to 5:", "B) for i in range(5):", "C) for i=1; i<=5;", "D) loop i from 0 to 5"], "answer": "B"},
{"category": "Lập trình", "question": "Thuật toán nào thường dùng để tìm kiếm nhanh trong danh sách đã sắp xếp?", "options": ["A) Linear Search", "B) Binary Search", "C) Bubble Sort", "D) DFS"], "answer": "B"},
{"category": "Lập trình", "question": "Trong OOP, khái niệm 'Encapsulation' là gì?", "options": ["A) Kế thừa", "B) Đóng gói dữ liệu và phương thức", "C) Đa hình", "D) Giao diện"], "answer": "B"},
{"category": "Lập trình", "question": "Git là công cụ dùng để làm gì?", "options": ["A) Thiết kế giao diện", "B) Quản lý phiên bản code", "C) Lưu trữ dữ liệu", "D) Truyền dữ liệu mạng"], "answer": "B"},
{"category": "Logic IQ", "question": "Nếu 2 + 3 = 10, 3 + 4 = 21, 4 + 5 = 36, theo quy luật, 5 + 6 = ?", "options": ["A) 45", "B) 55", "C) 66", "D) 65"], "answer": "B"},
{"category": "Logic IQ", "question": "Có 100 con chim trên cành, bắn 1 con chim, còn lại bao nhiêu?", "options": ["A) 99", "B) 100", "C) 0", "D) 50"], "answer": "C"},
{"category": "Logic IQ", "question": "Một người đi bộ 5km/h, xe đạp 15km/h, cùng xuất phát từ điểm A đến B cách 30km. Ai đến trước và sau bao lâu?", "options": ["A) Người đi bộ trước 6h", "B) Xe đạp trước 2h", "C) Người đi bộ trước 3h", "D) Xe đạp trước 3h"], "answer": "B"},
{"category": "Logic IQ", "question": "Tìm số tiếp theo trong dãy: 2, 4, 8, 16, ...", "options": ["A) 20", "B) 24", "C) 32", "D) 34"], "answer": "C"},
{"category": "Logic IQ", "question": "Nếu tất cả A là B, tất cả B là C, thì tất cả A là gì?", "options": ["A) B", "B) C", "C) Không xác định", "D) A"], "answer": "B"},
{"category": "Triết học", "question": "Chủ nghĩa duy vật biện chứng do ai phát triển?", "options": ["A) Hegel", "B) Marx và Engels", "C) Kant", "D) Descartes"], "answer": "B"},
{"category": "Triết học", "question": "Ai là tác giả của 'Hiện tượng học tinh thần'?", "options": ["A) Hegel", "B) Husserl", "C) Kant", "D) Descartes"], "answer": "B"},
{"category": "Triết học", "question": "Tư tưởng 'Con người là thước đo của vạn vật' thuộc ai?", "options": ["A) Protagoras", "B) Socrates", "C) Plato", "D) Aristotle"], "answer": "A"},
{"category": "Triết học", "question": "Khái niệm 'tabula rasa' là gì?", "options": ["A) Tờ giấy trắng, trí óc vô tri khi sinh ra", "B) Quy luật tự nhiên", "C) Học thuyết duy vật", "D) Học thuyết xã hội"], "answer": "A"},
{"category": "Triết học", "question": "Ai là người đặt nền móng cho triết học phương Tây cổ đại?", "options": ["A) Socrates", "B) Plato", "C) Aristotle", "D) Pythagoras"], "answer": "A"},
{"category": "Lịch sử thế giới", "question": "Ai là lãnh đạo Mỹ trong Chiến tranh thế giới thứ hai?", "options": ["A) Roosevelt", "B) Truman", "C) Eisenhower", "D) Kennedy"], "answer": "A"},
{"category": "Lịch sử thế giới", "question": "Cuộc Cách mạng Nga diễn ra năm nào?", "options": ["A) 1914", "B) 1917", "C) 1920", "D) 1923"], "answer": "B"},
{"category": "Lịch sử thế giới", "question": "Hiệp ước Versailles kết thúc chiến tranh nào?", "options": ["A) Chiến tranh thế giới thứ nhất", "B) Chiến tranh thế giới thứ hai", "C) Chiến tranh Napoleon", "D) Chiến tranh Pháp-Đức"], "answer": "A"},
{"category": "Lịch sử thế giới", "question": "Ai là thủ tướng Anh trong phần lớn Chiến tranh thế giới thứ hai?", "options": ["A) Churchill", "B) Chamberlain", "C) Blair", "D) Eden"], "answer": "A"},
{"category": "Lịch sử thế giới", "question": "Mặt trận Tây Âu trong Chiến tranh thế giới thứ nhất chủ yếu ở nước nào?", "options": ["A) Đức", "B) Pháp", "C) Bỉ", "D) Anh"], "answer": "B"},
{"category": "Toán học", "question": "Giá trị của biểu thức 5² - 3² là?", "options": ["A) 16", "B) 25", "C) 12", "D) 34"], "answer": "A"},
{"category": "Toán học", "question": "Tổng các số lẻ từ 1 đến 9 là?", "options": ["A) 20", "B) 25", "C) 30", "D) 35"], "answer": "B"},
{"category": "Toán học", "question": "Số nào là số nguyên tố?", "options": ["A) 21", "B) 29", "C) 33", "D) 35"], "answer": "B"},
{"category": "Toán học", "question": "Nghiệm của phương trình 2x + 7 = 15 là?", "options": ["A) 3", "B) 4", "C) 5", "D) 6"], "answer": "C"},
{"category": "Vật lý", "question": "Tốc độ ánh sáng trong chân không là?", "options": ["A) 3×10⁵ km/s", "B) 3×10⁸ m/s", "C) 3×10⁶ m/s", "D) 3×10⁷ km/s"], "answer": "B"},
{"category": "Vật lý", "question": "Đơn vị đo lực là gì?", "options": ["A) Watt", "B) Newton", "C) Pascal", "D) Joule"], "answer": "B"},
{"category": "Vật lý", "question": "Gia tốc rơi tự do trên Trái Đất xấp xỉ bao nhiêu?", "options": ["A) 9.8 m/s²", "B) 10 m/s²", "C) 9.0 m/s²", "D) 8.8 m/s²"], "answer": "A"},
{"category": "Vật lý", "question": "Hiện tượng khúc xạ ánh sáng xảy ra khi?", "options": ["A) Ánh sáng đi trong không khí", "B) Ánh sáng đi từ môi trường này sang môi trường khác", "C) Ánh sáng đi qua gương", "D) Ánh sáng phản xạ từ bề mặt"], "answer": "B"},
{"category": "Sinh học", "question": "Cơ quan nào chịu trách nhiệm lọc máu?", "options": ["A) Tim", "B) Thận", "C) Gan", "D) Phổi"], "answer": "B"},
{"category": "Sinh học", "question": "ADN chứa loại thông tin gì?", "options": ["A) Di truyền", "B) Cảm xúc", "C) Năng lượng", "D) Kháng thể"], "answer": "A"},
{"category": "Sinh học", "question": "Chức năng chính của hồng cầu là gì?", "options": ["A) Vận chuyển oxy", "B) Tạo kháng thể", "C) Tiết enzyme", "D) Lưu trữ mỡ"], "answer": "A"},
{"category": "Sinh học", "question": "Quá trình quang hợp diễn ra ở bộ phận nào của cây?", "options": ["A) Lá", "B) Rễ", "C) Thân", "D) Hoa"], "answer": "A"},
{"category": "Sinh học", "question": "Người trưởng thành có bao nhiêu cặp nhiễm sắc thể?", "options": ["A) 22", "B) 23", "C) 24", "D) 25"], "answer": "B"},
{"category": "Lịch sử", "question": "Ai là người sáng lập triều đại nhà Nguyễn?", "options": ["A) Nguyễn Huệ", "B) Gia Long", "C) Minh Mạng", "D) Tự Đức"], "answer": "B"},
{"category": "Lịch sử", "question": "Chiến tranh thế giới thứ hai kết thúc năm nào?", "options": ["A) 1944", "B) 1945", "C) 1946", "D) 1947"], "answer": "B"},
{"category": "Lịch sử", "question": "Ai là Tổng thống Mỹ trong Thế chiến II?", "options": ["A) Roosevelt", "B) Truman", "C) Eisenhower", "D) Kennedy"], "answer": "A"},
{"category": "Lịch sử", "question": "Cuộc Cách mạng Pháp bắt đầu năm nào?", "options": ["A) 1776", "B) 1789", "C) 1799", "D) 1804"], "answer": "B"},
{"category": "Lịch sử", "question": "Liên Xô tan rã vào năm nào?", "options": ["A) 1989", "B) 1990", "C) 1991", "D) 1992"], "answer": "C"},
{"category": "Địa lý", "question": "Thủ đô của Canada là gì?", "options": ["A) Toronto", "B) Vancouver", "C) Ottawa", "D) Montreal"], "answer": "C"},
{"category": "Địa lý", "question": "Sông dài nhất thế giới là gì?", "options": ["A) Nile", "B) Amazon", "C) Dương Tử", "D) Mississippi"], "answer": "A"},
{"category": "Địa lý", "question": "Quốc gia có diện tích lớn nhất thế giới là?", "options": ["A) Canada", "B) Nga", "C) Trung Quốc", "D) Mỹ"], "answer": "B"},
{"category": "Địa lý", "question": "Sa mạc lớn nhất thế giới là gì?", "options": ["A) Sahara", "B) Gobi", "C) Kalahari", "D) Atacama"], "answer": "A"},
{"category": "Địa lý", "question": "Vùng đất thấp nhất trên Trái Đất là?", "options": ["A) Thung lũng Chết", "B) Biển Chết", "C) Grand Canyon", "D) Hồ Baikal"], "answer": "B"},
{"category": "Văn học", "question": "Tác phẩm 'Truyện Kiều' gồm bao nhiêu câu thơ?", "options": ["A) 2548", "B) 3246", "C) 3254", "D) 3456"], "answer": "C"},
{"category": "Văn học", "question": "Ai là tác giả 'Nhật ký trong tù'?", "options": ["A) Tố Hữu", "B) Hồ Chí Minh", "C) Xuân Diệu", "D) Nam Cao"], "answer": "B"},
{"category": "Văn học", "question": "Tác phẩm 'Chiếc lược ngà' của ai?", "options": ["A) Nguyễn Minh Châu", "B) Nguyễn Quang Sáng", "C) Nam Cao", "D) Kim Lân"], "answer": "B"},
{"category": "Văn học", "question": "Nhân vật Chí Phèo xuất hiện trong tác phẩm nào?", "options": ["A) Số đỏ", "B) Lão Hạc", "C) Chí Phèo", "D) Đời thừa"], "answer": "C"},
{"category": "Văn học", "question": "Tác phẩm 'Romeo và Juliet' thuộc thể loại gì?", "options": ["A) Tiểu thuyết", "B) Truyện ngắn", "C) Bi kịch", "D) Anh hùng ca"], "answer": "C"},
{"category": "Công nghệ", "question": "Người sáng lập Microsoft là ai?", "options": ["A) Steve Jobs", "B) Bill Gates", "C) Elon Musk", "D) Larry Page"], "answer": "B"},
{"category": "Công nghệ", "question": "HTML dùng để làm gì?", "options": ["A) Tạo hình ảnh", "B) Thiết kế cấu trúc web", "C) Xử lý dữ liệu", "D) Lưu trữ video"], "answer": "B"},
{"category": "Công nghệ", "question": "GPU trong máy tính dùng để làm gì?", "options": ["A) Tính toán đồ họa", "B) Lưu trữ dữ liệu", "C) Truyền mạng", "D) Quản lý bộ nhớ"], "answer": "A"},
{"category": "Công nghệ", "question": "Công nghệ blockchain chủ yếu liên quan đến lĩnh vực nào?", "options": ["A) Mạng xã hội", "B) Tiền mã hóa", "C) Phần mềm văn phòng", "D) Trí tuệ nhân tạo"], "answer": "B"},
{"category": "Công nghệ", "question": "Python sử dụng dấu gì để kết thúc câu lệnh?", "options": ["A) ;", "B) :", "C) Không cần", "D) ."], "answer": "C"},
{"category": "Kinh tế", "question": "GDP là viết tắt của?", "options": ["A) General Domestic Price", "B) Gross Domestic Product", "C) Great Dynamic Power", "D) Government Development Plan"], "answer": "B"},
{"category": "Kinh tế", "question": "Ngân hàng Trung ương Việt Nam là?", "options": ["A) Vietcombank", "B) BIDV", "C) Ngân hàng Nhà nước Việt Nam", "D) Agribank"], "answer": "C"},
{"category": "Kinh tế", "question": "Lạm phát xảy ra khi điều gì tăng?", "options": ["A) Giá hàng hóa", "B) Lượng hàng tồn kho", "C) Giá trị tiền tệ", "D) Tỷ lệ thất nghiệp"], "answer": "A"},
{"category": "Kinh tế", "question": "Người được coi là cha đẻ kinh tế học hiện đại?", "options": ["A) Karl Marx", "B) Adam Smith", "C) Keynes", "D) Friedman"], "answer": "B"},
{"category": "Logic IQ", "question": "Nếu 3 con mèo bắt 3 con chuột trong 3 phút, 100 con mèo bắt 100 con chuột trong bao lâu?", "options": ["A) 1 phút", "B) 3 phút", "C) 100 phút", "D) 9 phút"], "answer": "B"},
{"category": "Logic IQ", "question": "Có 6 cái bánh chia cho 6 người, sao mỗi người có 1 cái mà vẫn còn 1 cái trong hộp?", "options": ["A) Một người lấy cả hộp", "B) Một cái vẫn trong hộp", "C) Một người không ăn", "D) Người cuối cùng lấy cả hộp"], "answer": "D"},
{"category": "Logic IQ", "question": "Số tiếp theo trong dãy: 1, 1, 2, 3, 5, 8, ...?", "options": ["A) 10", "B) 12", "C) 13", "D) 15"], "answer": "C"},
{"category": "Logic IQ", "question": "Một đồng hồ chạy nhanh 5 phút mỗi giờ. Nếu bây giờ đúng 12h, 3 giờ sau đồng hồ chỉ mấy giờ?", "options": ["A) 2:00", "B) 3:15", "C) 3:10", "D) 3:05"], "answer": "B"},
{"category": "Logic IQ", "question": "Nếu tất cả A là B, tất cả B là C, thì tất cả A là gì?", "options": ["A) B", "B) C", "C) Không xác định", "D) A"], "answer": "B"},
{"category": "Toán học", "question": "Giá trị của 7² - 4² là?", "options": ["A) 33", "B) 45", "C) 49", "D) 37"], "answer": "B"},
{"category": "Toán học", "question": "Tổng các số từ 1 đến 20 là?", "options": ["A) 190", "B) 200", "C) 210", "D) 220"], "answer": "C"},
{"category": "Toán học", "question": "Số nguyên tố nhỏ hơn 20 là số nào?", "options": ["A) 2,3,5,7,11,13,17,19", "B) 1,2,3,5,7,11,13,17", "C) 2,3,5,7,9,11,13,17", "D) 1,3,5,7,11,13,17"], "answer": "A"},
{"category": "Toán học", "question": "Giá trị của x nếu 3x + 5 = 20?", "options": ["A) 4", "B) 5", "C) 6", "D) 7"], "answer": "B"},
{"category": "Toán học", "question": "Diện tích hình chữ nhật dài 12cm, rộng 7cm là?", "options": ["A) 84 cm²", "B) 72 cm²", "C) 90 cm²", "D) 96 cm²"], "answer": "A"},
{"category": "Toán học", "question": "Nghiệm của x² - 16 = 0 là?", "options": ["A) 4", "B) -4", "C) ±4", "D) 0"], "answer": "C"},
{"category": "Toán học", "question": "Số trung bình cộng của 5, 10, 15 là?", "options": ["A) 10", "B) 12", "C) 11", "D) 9"], "answer": "A"},
{"category": "Toán học", "question": "Số tiếp theo trong dãy: 2, 4, 8, 16, ...?", "options": ["A) 18", "B) 24", "C) 32", "D) 36"], "answer": "C"},
{"category": "Toán học", "question": "Nếu 3x - 2 = 10 thì x bằng?", "options": ["A) 4", "B) 5", "C) 6", "D) 7"], "answer": "C"},
{"category": "Toán học", "question": "Số nghịch đảo của 5/8 là?", "options": ["A) 5/8", "B) 8/5", "C) -8/5", "D) -5/8"], "answer": "B"},
{"category": "Vật lý", "question": "Tốc độ ánh sáng trong chân không là?", "options": ["A) 3×10⁵ km/s", "B) 3×10⁸ m/s", "C) 3×10⁶ m/s", "D) 3×10⁷ km/s"], "answer": "B"},
{"category": "Vật lý", "question": "Đơn vị đo lực là gì?", "options": ["A) Newton", "B) Watt", "C) Pascal", "D) Joule"], "answer": "A"},
{"category": "Vật lý", "question": "Đơn vị đo công suất là gì?", "options": ["A) Watt", "B) Newton", "C) Pascal", "D) Joule"], "answer": "A"},
{"category": "Vật lý", "question": "Đơn vị đo năng lượng là gì?", "options": ["A) Joule", "B) Newton", "C) Watt", "D) Pascal"], "answer": "A"},
{"category": "Vật lý", "question": "Hiện tượng khúc xạ ánh sáng xảy ra khi?", "options": ["A) Ánh sáng đi qua không khí", "B) Ánh sáng đi từ môi trường này sang môi trường khác", "C) Ánh sáng phản xạ từ gương", "D) Ánh sáng bị tán xạ"], "answer": "B"},
{"category": "Vật lý", "question": "Hạt electron mang điện gì?", "options": ["A) Dương", "B) Âm", "C) Trung hòa", "D) Không xác định"], "answer": "B"},
{"category": "Vật lý", "question": "Gia tốc rơi tự do trên Trái Đất xấp xỉ bao nhiêu?", "options": ["A) 9.8 m/s²", "B) 10 m/s²", "C) 9.0 m/s²", "D) 8.8 m/s²"], "answer": "A"},
{"category": "Vật lý", "question": "Đơn vị đo điện trở là?", "options": ["A) Ohm", "B) Volt", "C) Ampere", "D) Watt"], "answer": "A"},
{"category": "Vật lý", "question": "Hiệu ứng quang điện chứng minh ánh sáng vừa là sóng vừa là hạt?", "options": ["A) Đúng", "B) Sai", "C) Chỉ là sóng", "D) Chỉ là hạt"], "answer": "A"},
{"category": "Sinh học", "question": "Hồng cầu có chức năng gì?", "options": ["A) Vận chuyển oxy", "B) Tạo kháng thể", "C) Tiết enzyme", "D) Dự trữ mỡ"], "answer": "A"},
{"category": "Sinh học", "question": "Cơ quan nào lọc máu?", "options": ["A) Tim", "B) Thận", "C) Gan", "D) Phổi"], "answer": "B"},
{"category": "Sinh học", "question": "ADN chứa thông tin gì?", "options": ["A) Di truyền", "B) Cảm xúc", "C) Năng lượng", "D) Kháng thể"], "answer": "A"},
{"category": "Sinh học", "question": "Quá trình quang hợp diễn ra ở?", "options": ["A) Lá", "B) Rễ", "C) Thân", "D) Hoa"], "answer": "A"},
{"category": "Sinh học", "question": "Người trưởng thành có bao nhiêu cặp nhiễm sắc thể?", "options": ["A) 22", "B) 23", "C) 24", "D) 25"], "answer": "B"},
{"category": "Lịch sử", "question": "Ai sáng lập triều đại nhà Nguyễn?", "options": ["A) Nguyễn Huệ", "B) Gia Long", "C) Minh Mạng", "D) Tự Đức"], "answer": "B"},
{"category": "Lịch sử", "question": "Chiến tranh thế giới thứ hai kết thúc năm nào?", "options": ["A) 1944", "B) 1945", "C) 1946", "D) 1947"], "answer": "B"},
{"category": "Lịch sử", "question": "Ai là Tổng thống Mỹ trong Thế chiến II?", "options": ["A) Roosevelt", "B) Truman", "C) Eisenhower", "D) Kennedy"], "answer": "A"},
{"category": "Lịch sử", "question": "Cuộc cách mạng Pháp bắt đầu năm nào?", "options": ["A) 1776", "B) 1789", "C) 1799", "D) 1804"], "answer": "B"},
{"category": "Lịch sử", "question": "Liên Xô tan rã năm nào?", "options": ["A) 1989", "B) 1990", "C) 1991", "D) 1992"], "answer": "C"},
{"category": "Địa lý", "question": "Thủ đô của Canada là gì?", "options": ["A) Toronto", "B) Vancouver", "C) Ottawa", "D) Montreal"], "answer": "C"},
{"category": "Địa lý", "question": "Sông dài nhất thế giới là gì?", "options": ["A) Nile", "B) Amazon", "C) Dương Tử", "D) Mississippi"], "answer": "A"},
{"category": "Địa lý", "question": "Quốc gia có diện tích lớn nhất thế giới?", "options": ["A) Canada", "B) Nga", "C) Trung Quốc", "D) Mỹ"], "answer": "B"},
{"category": "Địa lý", "question": "Sa mạc lớn nhất thế giới là gì?", "options": ["A) Sahara", "B) Gobi", "C) Kalahari", "D) Atacama"], "answer": "A"},
{"category": "Địa lý", "question": "Vùng đất thấp nhất trên Trái Đất là?", "options": ["A) Thung lũng Chết", "B) Biển Chết", "C) Grand Canyon", "D) Hồ Baikal"], "answer": "B"},
{"category": "Văn học", "question": "Tác phẩm 'Truyện Kiều' gồm bao nhiêu câu thơ?", "options": ["A) 2548", "B) 3246", "C) 3254", "D) 3456"], "answer": "C"},
{"category": "Văn học", "question": "Ai là tác giả 'Nhật ký trong tù'?", "options": ["A) Tố Hữu", "B) Hồ Chí Minh", "C) Xuân Diệu", "D) Nam Cao"], "answer": "B"},
{"category": "Văn học", "question": "Tác phẩm 'Chiếc lược ngà' của ai?", "options": ["A) Nguyễn Minh Châu", "B) Nguyễn Quang Sáng", "C) Nam Cao", "D) Kim Lân"], "answer": "B"},

]
