quiz_questions = [
    # ==================== ĐỊA LÝ ====================
    {"category": "Địa lý", "question": "Thủ đô của Canada là gì?", "options": ["A) Toronto", "B) Vancouver", "C) Ottawa", "D) Montreal"], "answer": "C"},
    {"category": "Địa lý", "question": "Sông dài nhất thế giới là gì?", "options": ["A) Nile", "B) Amazon", "C) Dương Tử", "D) Mississippi"], "answer": "A"},
    {"category": "Địa lý", "question": "Đỉnh núi cao nhất thế giới là gì?", "options": ["A) Everest", "B) K2", "C) Kangchenjunga", "D) Lhotse"], "answer": "A"},
    {"category": "Địa lý", "question": "Sa mạc lớn nhất thế giới là gì?", "options": ["A) Sahara", "B) Gobi", "C) Kalahari", "D) Atacama"], "answer": "A"},
    {"category": "Địa lý", "question": "Quốc gia có diện tích lớn nhất thế giới là?", "options": ["A) Canada", "B) Nga", "C) Trung Quốc", "D) Mỹ"], "answer": "B"},

    # ==================== LỊCH SỬ ====================
    {"category": "Lịch sử", "question": "Chiến tranh thế giới thứ hai kết thúc vào năm nào?", "options": ["A) 1943", "B) 1944", "C) 1945", "D) 1946"], "answer": "C"},
    {"category": "Lịch sử", "question": "Ai là người sáng lập ra triều đại nhà Nguyễn?", "options": ["A) Gia Long", "B) Minh Mạng", "C) Tự Đức", "D) Thiệu Trị"], "answer": "A"},
    {"category": "Lịch sử", "question": "Cách mạng tháng Mười Nga diễn ra năm nào?", "options": ["A) 1914", "B) 1917", "C) 1920", "D) 1939"], "answer": "B"},
    {"category": "Lịch sử", "question": "Người đầu tiên đặt chân lên Mặt Trăng là ai?", "options": ["A) Yuri Gagarin", "B) Neil Armstrong", "C) Buzz Aldrin", "D) John Glenn"], "answer": "B"},
    {"category": "Lịch sử", "question": "Chiến tranh Việt Nam kết thúc năm nào?", "options": ["A) 1973", "B) 1974", "C) 1975", "D) 1976"], "answer": "C"},

    # ==================== TOÁN HỌC ====================
    {"category": "Toán học", "question": "Giá trị của 12 × 8 là bao nhiêu?", "options": ["A) 80", "B) 96", "C) 108", "D) 88"], "answer": "B"},
    {"category": "Toán học", "question": "Căn bậc hai của 81 là gì?", "options": ["A) 8", "B) 9", "C) 10", "D) 7"], "answer": "B"},
    {"category": "Toán học", "question": "Giá trị của π (pi) xấp xỉ là?", "options": ["A) 2.14", "B) 3.14", "C) 4.13", "D) 3.41"], "answer": "B"},
    {"category": "Toán học", "question": "5! (5 giai thừa) bằng bao nhiêu?", "options": ["A) 20", "B) 60", "C) 120", "D) 240"], "answer": "C"},
    {"category": "Toán học", "question": "Bình phương của 15 là?", "options": ["A) 125", "B) 200", "C) 215", "D) 225"], "answer": "D"},

    # ==================== VẬT LÝ ====================
    {"category": "Vật lý", "question": "Đơn vị của lực là gì?", "options": ["A) Joule", "B) Watt", "C) Newton", "D) Pascal"], "answer": "C"},
    {"category": "Vật lý", "question": "Tốc độ ánh sáng là bao nhiêu?", "options": ["A) 3×10⁶ m/s", "B) 3×10⁸ m/s", "C) 3×10⁹ m/s", "D) 3×10⁷ m/s"], "answer": "B"},
    {"category": "Vật lý", "question": "Ai là người phát minh ra bóng đèn điện?", "options": ["A) Edison", "B) Newton", "C) Tesla", "D) Faraday"], "answer": "A"},
    {"category": "Vật lý", "question": "Chất nào dẫn điện tốt nhất?", "options": ["A) Sắt", "B) Vàng", "C) Đồng", "D) Bạc"], "answer": "D"},
    {"category": "Vật lý", "question": "Nhiệt độ sôi của nước ở điều kiện tiêu chuẩn là?", "options": ["A) 90°C", "B) 95°C", "C) 100°C", "D) 105°C"], "answer": "C"},

    # ==================== ĐỐ MẸO ====================
    {"category": "Đố mẹo", "question": "Cái gì càng lấy đi càng lớn?", "options": ["A) Lỗ hổng", "B) Cái chén", "C) Cái bát", "D) Cái nhà"], "answer": "A"},
    {"category": "Đố mẹo", "question": "Cái gì có đầu mà không có cổ?", "options": ["A) Cái ghế", "B) Cái gối", "C) Cái bàn", "D) Cái dép"], "answer": "B"},
    {"category": "Đố mẹo", "question": "Con gì không bao giờ ngủ?", "options": ["A) Con sông", "B) Con gà", "C) Con chó", "D) Con mèo"], "answer": "A"},
    {"category": "Đố mẹo", "question": "Thứ gì càng rửa càng bẩn?", "options": ["A) Nước", "B) Giẻ lau", "C) Cái chổi", "D) Quần áo"], "answer": "A"},
    {"category": "Đố mẹo", "question": "Con gì đi bằng 4 chân lúc bé, 2 chân lúc lớn, 3 chân lúc già?", "options": ["A) Con người", "B) Con chó", "C) Con mèo", "D) Con ngựa"], "answer": "A"},

    # ==================== ĐỐ VUI ====================
    {"category": "Đố vui", "question": "Trên đồng có 6 con trâu, 3 con đi ra, hỏi còn mấy con?", "options": ["A) 3", "B) 6", "C) 9", "D) 0"], "answer": "B"},
    {"category": "Đố vui", "question": "Cái gì người ta mua để ăn nhưng không ăn được?", "options": ["A) Cái đĩa", "B) Cái muỗng", "C) Cái chén", "D) Cái bàn"], "answer": "A"},
    {"category": "Đố vui", "question": "Cái gì luôn đi mà không bao giờ đến?", "options": ["A) Tương lai", "B) Con đường", "C) Cái đồng hồ", "D) Cơn mưa"], "answer": "A"},
    {"category": "Đố vui", "question": "Cái gì có thể chứa nước nhưng không bao giờ ướt?", "options": ["A) Cái ly", "B) Cái bản đồ", "C) Cái xô", "D) Cái chai"], "answer": "B"},
    {"category": "Đố vui", "question": "Cái gì càng chạy càng nhỏ?", "options": ["A) Ngọn lửa", "B) Dòng sông", "C) Cái quạt", "D) Cái bóng"], "answer": "D"},
    {"category": "Đố vui", "question": "Cái gì luôn đi mà không bao giờ đến?", "options": ["A) Tương lai", "B) Con đường", "C) Cái đồng hồ", "D) Cơn mưa"], "answer": "A"},
    {"category": "Khoa học", "question": "Nước sôi ở bao nhiêu độ C tại mực nước biển?", "options": ["A) 90", "B) 95", "C) 100", "D) 110"], "answer": "C"},
    {"category": "Địa lý", "question": "Thủ đô của Nhật Bản là gì?", "options": ["A) Kyoto", "B) Tokyo", "C) Osaka", "D) Nagoya"], "answer": "B"},
    {"category": "Văn học", "question": "Tác giả của truyện 'Lão Hạc' là ai?", "options": ["A) Nam Cao", "B) Ngô Tất Tố", "C) Kim Lân", "D) Nguyễn Công Hoan"], "answer": "A"},
    {"category": "Lịch sử", "question": "Chiến thắng Điện Biên Phủ diễn ra năm nào?", "options": ["A) 1954", "B) 1945", "C) 1975", "D) 1968"], "answer": "A"},
    {"category": "Toán học", "question": "Căn bậc hai của 49 là bao nhiêu?", "options": ["A) 6", "B) 7", "C) 8", "D) 9"], "answer": "B"},
    {"category": "Đố vui", "question": "Con gì càng rửa càng bẩn?", "options": ["A) Cái áo", "B) Cái chân", "C) Cái chổi", "D) Cái sông"], "answer": "C"},
    {"category": "Âm nhạc", "question": "Nhạc sĩ Trịnh Công Sơn nổi tiếng với thể loại nhạc nào?", "options": ["A) Rock", "B) Trữ tình", "C) Rap", "D) Jazz"], "answer": "B"},
    {"category": "Công nghệ", "question": "CPU là viết tắt của từ gì?", "options": ["A) Central Processing Unit", "B) Computer Power Unit", "C) Core Performance Unit", "D) Central Program Utility"], "answer": "A"},
    {"category": "Thể thao", "question": "Một trận bóng đá có bao nhiêu cầu thủ trên sân mỗi đội?", "options": ["A) 10", "B) 11", "C) 12", "D) 9"], "answer": "B"},
    {"category": "Đố vui", "question": "Con gì biết bay mà không có cánh?", "options": ["A) Máy bay", "B) Thời gian", "C) Bóng bay", "D) Tư tưởng"], "answer": "B"},
    {"category": "Khoa học", "question": "Nguyên tố có ký hiệu O là gì?", "options": ["A) Oxi", "B) Vàng", "C) Sắt", "D) Bạc"], "answer": "A"},
    {"category": "Địa lý", "question": "Sông dài nhất Việt Nam là sông nào?", "options": ["A) Sông Hồng", "B) Sông Mekong", "C) Sông Đồng Nai", "D) Sông Cửu Long"], "answer": "A"},
    {"category": "Văn học", "question": "Nhân vật Chí Phèo xuất hiện trong tác phẩm nào?", "options": ["A) Tắt đèn", "B) Lão Hạc", "C) Chí Phèo", "D) Số đỏ"], "answer": "C"},
    {"category": "Lịch sử", "question": "Bác Hồ đọc Tuyên ngôn Độc lập tại đâu?", "options": ["A) Quảng trường Ba Đình", "B) Nhà hát lớn", "C) Hồ Gươm", "D) Văn Miếu"], "answer": "A"},
    {"category": "Toán học", "question": "Pi (π) có giá trị gần đúng là bao nhiêu?", "options": ["A) 2.14", "B) 3.14", "C) 3.41", "D) 4.13"], "answer": "B"},
    {"category": "Đố vui", "question": "Cái gì càng lấy đi thì càng lớn?", "options": ["A) Cái hố", "B) Cái nhà", "C) Cái bàn", "D) Cái ghế"], "answer": "A"},
    {"category": "Âm nhạc", "question": "Nhạc cụ nào có phím đen và trắng?", "options": ["A) Trống", "B) Ghi-ta", "C) Piano", "D) Sáo"], "answer": "C"},
    {"category": "Công nghệ", "question": "Hệ điều hành Android thuộc công ty nào?", "options": ["A) Microsoft", "B) Google", "C) Apple", "D) Samsung"], "answer": "B"},
    {"category": "Thể thao", "question": "Quốc gia nào vô địch World Cup 2018?", "options": ["A) Đức", "B) Pháp", "C) Brazil", "D) Argentina"], "answer": "B"},
    {"category": "Đố vui", "question": "Cái gì có cổ mà không có đầu?", "options": ["A) Cái chai", "B) Con rắn", "C) Cái bàn", "D) Cái cây"], "answer": "A"},
    {"category": "Khoa học", "question": "Trái Đất quay quanh Mặt Trời mất bao lâu?", "options": ["A) 24 giờ", "B) 7 ngày", "C) 30 ngày", "D) 365 ngày"], "answer": "D"},
    {"category": "Địa lý", "question": "Sa mạc lớn nhất thế giới là sa mạc nào?", "options": ["A) Sahara", "B) Gobi", "C) Kalahari", "D) Arab"], "answer": "A"},
    {"category": "Văn học", "question": "Ai là tác giả 'Truyện Kiều'?", "options": ["A) Nguyễn Du", "B) Nguyễn Trãi", "C) Nguyễn Đình Chiểu", "D) Hồ Xuân Hương"], "answer": "A"},
    {"category": "Lịch sử", "question": "Chiến dịch Hồ Chí Minh kết thúc vào năm nào?", "options": ["A) 1975", "B) 1973", "C) 1968", "D) 1945"], "answer": "A"},
    {"category": "Toán học", "question": "Kết quả của 12 × 8 là bao nhiêu?", "options": ["A) 80", "B) 96", "C) 108", "D) 120"], "answer": "B"},
    {"category": "Đố vui", "question": "Con gì đứng mà không ngồi, nằm mà không đứng?", "options": ["A) Cái bàn", "B) Cái giường", "C) Cái cây", "D) Cái thước"], "answer": "B"},
    {"category": "Âm nhạc", "question": "Ca sĩ Mỹ Tâm nổi tiếng với biệt danh gì?", "options": ["A) Họa mi tóc nâu", "B) Nữ hoàng nhạc trẻ", "C) Nữ hoàng V-Pop", "D) Thiên thần âm nhạc"], "answer": "A"},
    {"category": "Công nghệ", "question": "Ngôn ngữ lập trình Python được đặt tên theo cái gì?", "options": ["A) Con rắn", "B) Một chương trình TV", "C) Tác giả Python", "D) Một ngọn núi"], "answer": "B"},
    {"category": "Thể thao", "question": "Sân bóng rổ có bao nhiêu người mỗi đội trên sân?", "options": ["A) 4", "B) 5", "C) 6", "D) 7"], "answer": "B"},
    {"category": "Đố vui", "question": "Cái gì càng cắt càng dài?", "options": ["A) Cái tóc", "B) Cái dây", "C) Đường đi", "D) Câu chuyện"], "answer": "D"},
    {"category": "Khoa học", "question": "Tế bào là đơn vị cơ bản của cái gì?", "options": ["A) Cơ thể sống", "B) Nguyên tử", "C) Hành tinh", "D) Khoáng chất"], "answer": "A"},
    {"category": "Địa lý", "question": "Thủ đô của Thái Lan là gì?", "options": ["A) Bangkok", "B) Chiang Mai", "C) Pattaya", "D) Phuket"], "answer": "A"},
    {"category": "Văn học", "question": "Nhà thơ Xuân Diệu thuộc phong trào nào?", "options": ["A) Thơ mới", "B) Cách mạng", "C) Hiện đại", "D) Lãng mạn"], "answer": "A"},
    {"category": "Lịch sử", "question": "Năm 1945, Việt Nam giành được độc lập vào ngày nào?", "options": ["A) 19/8", "B) 2/9", "C) 1/9", "D) 10/10"], "answer": "B"},
    {"category": "Toán học", "question": "Tổng của các góc trong tam giác bằng bao nhiêu độ?", "options": ["A) 90", "B) 120", "C) 180", "D) 270"], "answer": "C"},
    {"category": "Đố vui", "question": "Cái gì càng đầy càng nhẹ?", "options": ["A) Cái túi khí", "B) Cái hộp", "C) Bóng bay", "D) Cái chai"], "answer": "C"},
    {"category": "Âm nhạc", "question": "Nhạc cụ nào có dây mà không có phím?", "options": ["A) Violin", "B) Guitar", "C) Piano", "D) Harp"], "answer": "A"},
    {"category": "Công nghệ", "question": "RAM là viết tắt của gì?", "options": ["A) Random Access Memory", "B) Read All Memory", "C) Run Active Module", "D) Ready Access Mode"], "answer": "A"},
    {"category": "Thể thao", "question": "Cầu thủ nào được gọi là 'Vua bóng đá'?", "options": ["A) Pele", "B) Messi", "C) Ronaldo", "D) Maradona"], "answer": "A"},
    {"category": "Đố vui", "question": "Cái gì có một chân mà không thể đi?", "options": ["A) Cái ghế", "B) Cái bàn", "C) Cái đèn", "D) Cái chén"], "answer": "C"},
    {"category": "Khoa học", "question": "Khí nào cần cho sự hô hấp của con người?", "options": ["A) Nitơ", "B) Oxi", "C) Cacbon", "D) Heli"], "answer": "B"},
    {"category": "Địa lý", "question": "Châu lục lớn nhất thế giới là gì?", "options": ["A) Châu Á", "B) Châu Âu", "C) Châu Phi", "D) Châu Mỹ"], "answer": "A"},
    {"category": "Văn học", "question": "Nhân vật Tấm thuộc truyện nào?", "options": ["A) Tấm Cám", "B) Thạch Sanh", "C) Cây tre trăm đốt", "D) Sọ Dừa"], "answer": "A"},
    {"category": "Lịch sử", "question": "Ai là người sáng lập ra Đảng Cộng sản Việt Nam?", "options": ["A) Phạm Văn Đồng", "B) Võ Nguyên Giáp", "C) Hồ Chí Minh", "D) Trường Chinh"], "answer": "C"},
    {"category": "Toán học", "question": "Giá trị của 5² là bao nhiêu?", "options": ["A) 10", "B) 20", "C) 25", "D) 30"], "answer": "C"},
    {"category": "Đố vui", "question": "Cái gì chỉ có một mà ai cũng có hai?", "options": ["A) Con mắt", "B) Cái tai", "C) Cái tay", "D) Cái chân"], "answer": "C"},
    {"category": "Âm nhạc", "question": "Bài hát quốc ca Việt Nam có tên là gì?", "options": ["A) Vì một thế giới ngày mai", "B) Tiến quân ca", "C) Như có Bác trong ngày vui đại thắng", "D) Nối vòng tay lớn"], "answer": "B"},
    {"category": "Công nghệ", "question": "Hãng nào sản xuất iPhone?", "options": ["A) Samsung", "B) Apple", "C) Huawei", "D) Xiaomi"], "answer": "B"},
    {"category": "Thể thao", "question": "Bóng rổ được chơi bằng gì?", "options": ["A) Chân", "B) Tay", "C) Đầu", "D) Cả ba"], "answer": "B"},
    {"category": "Đố vui", "question": "Cái gì càng rửa càng dơ?", "options": ["A) Nước", "B) Cái khăn", "C) Cái bát", "D) Cái nhà"], "answer": "B"},
    {"category": "Khoa học", "question": "Nguyên tố có ký hiệu H là gì?", "options": ["A) Heli", "B) Hidro", "C) Hạt nhân", "D) Hiđrôxít"], "answer": "B"},
    {"category": "Địa lý", "question": "Sông nào dài nhất thế giới?", "options": ["A) Nile", "B) Amazon", "C) Mississippi", "D) Yangtze"], "answer": "A"},
    {"category": "Văn học", "question": "Tác phẩm 'Số đỏ' là của ai?", "options": ["A) Vũ Trọng Phụng", "B) Nam Cao", "C) Ngô Tất Tố", "D) Nguyễn Tuân"], "answer": "A"},
    {"category": "Lịch sử", "question": "Năm 1975, Việt Nam thống nhất đất nước sau chiến dịch nào?", "options": ["A) Hồ Chí Minh", "B) Điện Biên Phủ", "C) Tây Nguyên", "D) Quảng Trị"], "answer": "A"},
    {"category": "Toán học", "question": "Số nhỏ nhất chia hết cho 2 và 3 là gì?", "options": ["A) 3", "B) 6", "C) 9", "D) 12"], "answer": "B"},
    {"category": "Đố vui", "question": "Con gì có 4 chân nhưng không biết đi?", "options": ["A) Cái ghế", "B) Con rùa", "C) Con bàn", "D) Cái bàn"], "answer": "D"},
    {"category": "Âm nhạc", "question": "Ca sĩ Sơn Tùng M-TP quê ở đâu?", "options": ["A) Hà Nội", "B) Thái Bình", "C) TP.HCM", "D) Hải Phòng"], "answer": "B"},
    {"category": "Công nghệ", "question": "Facebook được sáng lập bởi ai?", "options": ["A) Elon Musk", "B) Bill Gates", "C) Mark Zuckerberg", "D) Steve Jobs"], "answer": "C"},
    {"category": "Thể thao", "question": "Mỗi hiệp bóng đá kéo dài bao lâu?", "options": ["A) 30 phút", "B) 45 phút", "C) 50 phút", "D) 60 phút"], "answer": "B"},
    {"category": "Đố vui", "question": "Cái gì có mặt mà không có mũi?", "options": ["A) Cái bàn", "B) Cái đồng hồ", "C) Cái ghế", "D) Cái đĩa"], "answer": "B"},
    {"category": "Khoa học", "question": "Thực vật hấp thụ khí nào để quang hợp?", "options": ["A) CO2", "B) O2", "C) H2", "D) N2"], "answer": "A"},
    {"category": "Địa lý", "question": "Thủ đô của Campuchia là gì?", "options": ["A) Vientiane", "B) Phnom Penh", "C) Bangkok", "D) Yangon"], "answer": "B"},
    {"category": "Văn học", "question": "Ai là tác giả 'Vợ nhặt'?", "options": ["A) Kim Lân", "B) Nam Cao", "C) Ngô Tất Tố", "D) Tô Hoài"], "answer": "A"},
    {"category": "Lịch sử", "question": "Bác Hồ ra đi tìm đường cứu nước năm nào?", "options": ["A) 1911", "B) 1920", "C) 1930", "D) 1941"], "answer": "A"},
    {"category": "Toán học", "question": "Bội chung nhỏ nhất của 4 và 6 là gì?", "options": ["A) 10", "B) 12", "C) 14", "D) 16"], "answer": "B"},
    {"category": "Đố vui", "question": "Cái gì có tay mà không biết vỗ?", "options": ["A) Cái áo", "B) Cái bàn", "C) Cái đồng hồ", "D) Cái ghế"], "answer": "A"},
    {"category": "Âm nhạc", "question": "Nhạc sĩ Văn Cao sáng tác bài nào sau đây?", "options": ["A) Tiến quân ca", "B) Hà Nội mùa vắng những cơn mưa", "C) Tình ca", "D) Diễm xưa"], "answer": "A"},
    {"category": "Công nghệ", "question": "Microsoft do ai sáng lập?", "options": ["A) Steve Jobs", "B) Bill Gates", "C) Elon Musk", "D) Jeff Bezos"], "answer": "B"},
    {"category": "Thể thao", "question": "Môn thể thao vua là môn gì?", "options": ["A) Bóng đá", "B) Bóng chuyền", "C) Cầu lông", "D) Bóng rổ"], "answer": "A"},
    {"category": "Đố vui", "question": "Cái gì không có chân mà vẫn chạy?", "options": ["A) Dòng sông", "B) Gió", "C) Xe hơi", "D) Máy bay"], "answer": "A"},
    {"category": "Khoa học", "question": "Âm thanh truyền nhanh nhất trong môi trường nào?", "options": ["A) Không khí", "B) Nước", "C) Rắn", "D) Chân không"], "answer": "C"},
    {"category": "Địa lý", "question": "Núi cao nhất thế giới là gì?", "options": ["A) Everest", "B) Phan Xi Păng", "C) Fuji", "D) Andes"], "answer": "A"},
    {"category": "Văn học", "question": "Tác phẩm 'Dế Mèn phiêu lưu ký' của ai?", "options": ["A) Tô Hoài", "B) Nam Cao", "C) Nguyễn Nhật Ánh", "D) Kim Lân"], "answer": "A"},
    {"category": "Lịch sử", "question": "Chiến dịch Điện Biên Phủ diễn ra ở vùng nào?", "options": ["A) Tây Bắc", "B) Đông Bắc", "C) Trung Bộ", "D) Nam Bộ"], "answer": "A"},
    {"category": "Toán học", "question": "Giá trị của 9 × 9 là bao nhiêu?", "options": ["A) 80", "B) 81", "C) 90", "D) 99"], "answer": "B"},
    {"category": "Đố vui", "question": "Cái gì có nhiều răng nhưng không ăn được?", "options": ["A) Lược", "B) Cái cưa", "C) Cả hai đáp án trên", "D) Cái bàn"], "answer": "C"},
    {"category": "Âm nhạc", "question": "Bài hát 'Nối vòng tay lớn' do ai sáng tác?", "options": ["A) Trịnh Công Sơn", "B) Văn Cao", "C) Phạm Duy", "D) Nguyễn Ánh 9"], "answer": "A"},
    {"category": "Công nghệ", "question": "Logo của hệ điều hành Android có hình gì?", "options": ["A) Quả táo", "B) Con robot", "C) Con chim", "D) Trái đất"], "answer": "B"},
    {"category": "Thể thao", "question": "Quả bóng vàng là giải thưởng trong môn nào?", "options": ["A) Bóng rổ", "B) Bóng đá", "C) Tennis", "D) Bóng chuyền"], "answer": "B"},
    {"category": "Đố vui", "question": "Cái gì có miệng mà không nói được?", "options": ["A) Con cá", "B) Dòng sông", "C) Cái ly", "D) Cái cốc"], "answer": "B"},
    {"category": "Khoa học", "question": "Mặt Trăng là vệ tinh của hành tinh nào?", "options": ["A) Sao Hỏa", "B) Trái Đất", "C) Sao Kim", "D) Sao Thủy"], "answer": "B"},
    {"category": "Địa lý", "question": "Biển Đông giáp bao nhiêu quốc gia?", "options": ["A) 4", "B) 6", "C) 8", "D) 9"], "answer": "C"},
    {"category": "Văn học", "question": "Ai là tác giả 'Cho tôi xin một vé đi tuổi thơ'?", "options": ["A) Nguyễn Nhật Ánh", "B) Nam Cao", "C) Tô Hoài", "D) Kim Lân"], "answer": "A"},
    {"category": "Lịch sử", "question": "Nhà Trần nổi tiếng với chiến thắng nào?", "options": ["A) Chiến thắng Bạch Đằng", "B) Chiến thắng Đống Đa", "C) Chiến thắng Chi Lăng", "D) Chiến thắng Hàm Tử"], "answer": "A"},
    {"category": "Toán học", "question": "5 + 7 × 2 = ?", "options": ["A) 19", "B) 24", "C) 26", "D) 17"], "answer": "A"},
    {"category": "Đố vui", "question": "Cái gì có thể bay mà không có cánh?", "options": ["A) Gió", "B) Mây", "C) Thời gian", "D) Tư tưởng"], "answer": "C"},
    {"category": "Âm nhạc", "question": "Ca sĩ nào được mệnh danh là 'Hoàng tử V-Pop'?", "options": ["A) Noo Phước Thịnh", "B) Sơn Tùng M-TP", "C) Erik", "D) Isaac"], "answer": "B"},
    {"category": "Công nghệ", "question": "Google được thành lập vào năm nào?", "options": ["A) 1995", "B) 1998", "C) 2000", "D) 2003"], "answer": "B"},
    {"category": "Thể thao", "question": "Quần vợt còn được gọi là gì?", "options": ["A) Tennis", "B) Golf", "C) Ping pong", "D) Badminton"], "answer": "A"},
    {"category": "Đố vui", "question": "Cái gì càng đập càng nhỏ?", "options": ["A) Đá", "B) Thủy tinh", "C) Bột", "D) Cả ba"], "answer": "D"},
    {"category": "Khoa học", "question": "Mặt Trời là gì?", "options": ["A) Ngôi sao", "B) Hành tinh", "C) Vệ tinh", "D) Sao chổi"], "answer": "A"},
    {"category": "Địa lý", "question": "Thủ đô của Lào là gì?", "options": ["A) Vientiane", "B) Phnom Penh", "C) Yangon", "D) Bangkok"], "answer": "A"},
    {"category": "Văn học", "question": "Tác phẩm 'Nhật ký trong tù' của ai?", "options": ["A) Hồ Chí Minh", "B) Phan Bội Châu", "C) Nguyễn Trãi", "D) Tố Hữu"], "answer": "A"},
    {"category": "Lịch sử", "question": "Nước ta chính thức đổi tên thành Cộng hòa Xã hội Chủ nghĩa Việt Nam năm nào?", "options": ["A) 1976", "B) 1975", "C) 1980", "D) 1986"], "answer": "A"},
    {"category": "Toán học", "question": "Diện tích hình vuông có cạnh 5 là bao nhiêu?", "options": ["A) 10", "B) 20", "C) 25", "D) 30"], "answer": "C"},
    {"category": "Đố vui", "question": "Cái gì càng khô càng ướt?", "options": ["A) Cái khăn", "B) Cái áo", "C) Cái bàn", "D) Cái sông"], "answer": "A"},
    {"category": "Âm nhạc", "question": "Nhạc cụ nào dùng dùi để gõ?", "options": ["A) Piano", "B) Trống", "C) Sáo", "D) Guitar"], "answer": "B"},
    {"category": "Công nghệ", "question": "USB dùng để làm gì?", "options": ["A) Lưu trữ dữ liệu", "B) Nghe nhạc", "C) Gọi điện", "D) Xem phim"], "answer": "A"},
    {"category": "Thể thao", "question": "Trong bóng đá, thẻ vàng dùng để làm gì?", "options": ["A) Khen thưởng", "B) Cảnh cáo", "C) Đuổi ra sân", "D) Thay người"], "answer": "B"},
    {"category": "Đố vui", "question": "Cái gì có mắt mà không thấy?", "options": ["A) Cái kim", "B) Cơn bão", "C) Cả hai", "D) Cái cốc"], "answer": "C"},
    {"category": "Khoa học", "question": "Lực hút giữa các vật gọi là gì?", "options": ["A) Ma sát", "B) Hấp dẫn", "C) Đẩy", "D) Quán tính"], "answer": "B"},
    {"category": "Địa lý", "question": "Thủ đô của Anh là gì?", "options": ["A) London", "B) Paris", "C) Rome", "D) Berlin"], "answer": "A"},
    {"category": "Văn học", "question": "Nhà thơ Hàn Mặc Tử nổi tiếng với chủ đề gì?", "options": ["A) Tình yêu", "B) Cách mạng", "C) Chiến tranh", "D) Thiên nhiên"], "answer": "A"},
    {"category": "Lịch sử", "question": "Người Việt cổ sinh sống chủ yếu bằng nghề gì?", "options": ["A) Săn bắt", "B) Nông nghiệp", "C) Thương mại", "D) Chăn nuôi"], "answer": "B"},
    {"category": "Toán học", "question": "Phân số 1/2 bằng bao nhiêu phần trăm?", "options": ["A) 25%", "B) 50%", "C) 75%", "D) 100%"], "answer": "B"},
    {"category": "Đố vui", "question": "Cái gì càng đi càng nhỏ?", "options": ["A) Dấu chân", "B) Cái bóng", "C) Hạt mưa", "D) Cả hai"], "answer": "A"},
    {"category": "Âm nhạc", "question": "Ca sĩ nào được gọi là 'Ông hoàng nhạc Việt'?", "options": ["A) Đàm Vĩnh Hưng", "B) Tuấn Hưng", "C) Lam Trường", "D) Trấn Thành"], "answer": "A"},
    {"category": "Công nghệ", "question": "Phần mềm diệt virus nổi tiếng nhất là gì?", "options": ["A) Avast", "B) Chrome", "C) Word", "D) Spotify"], "answer": "A"},
    {"category": "Thể thao", "question": "Sân tennis được chia làm mấy nửa?", "options": ["A) 1", "B) 2", "C) 3", "D) 4"], "answer": "B"},
    {"category": "Đố vui", "question": "Con gì sống trên trời nhưng lại rơi xuống đất?", "options": ["A) Mưa", "B) Tuyết", "C) Cả hai", "D) Chim"], "answer": "C"},
    {"category": "Khoa học", "question": "Cơ quan nào giúp con người hô hấp?", "options": ["A) Tim", "B) Phổi", "C) Gan", "D) Dạ dày"], "answer": "B"},
    {"category": "Địa lý", "question": "Sông Mekong chảy qua bao nhiêu quốc gia?", "options": ["A) 4", "B) 5", "C) 6", "D) 7"], "answer": "C"},
    {"category": "Văn học", "question": "Tác phẩm 'Tắt đèn' nói về tầng lớp nào?", "options": ["A) Nông dân", "B) Công nhân", "C) Trí thức", "D) Quý tộc"], "answer": "A"},
    {"category": "Lịch sử", "question": "Trận Bạch Đằng nổi tiếng thuộc triều đại nào?", "options": ["A) Ngô Quyền", "B) Lê Lợi", "C) Trần Nhân Tông", "D) Quang Trung"], "answer": "A"},
    {"category": "Toán học", "question": "Chu vi hình vuông cạnh 4 là bao nhiêu?", "options": ["A) 8", "B) 12", "C) 16", "D) 20"], "answer": "C"},
    {"category": "Đố vui", "question": "Cái gì luôn chạy mà không biết mệt?", "options": ["A) Dòng sông", "B) Xe máy", "C) Gió", "D) Đồng hồ"], "answer": "D"},
    {"category": "Âm nhạc", "question": "Ca sĩ nào hát bài 'Em của ngày hôm qua'?", "options": ["A) Sơn Tùng M-TP", "B) Noo Phước Thịnh", "C) Erik", "D) Jack"], "answer": "A"},
    {"category": "Công nghệ", "question": "TikTok là ứng dụng của quốc gia nào?", "options": ["A) Mỹ", "B) Trung Quốc", "C) Nhật Bản", "D) Hàn Quốc"], "answer": "B"},
    {"category": "Thể thao", "question": "Olympic tổ chức bao nhiêu năm một lần?", "options": ["A) 2", "B) 3", "C) 4", "D) 5"], "answer": "C"},
    {"category": "Đố vui", "question": "Cái gì bạn chỉ có thể cho mà không thể lấy lại?", "options": ["A) Lời nói", "B) Tiền", "C) Tình yêu", "D) Quà"], "answer": "A"},
    {"category": "Khoa học", "question": "Nước chiếm bao nhiêu phần trăm cơ thể người?", "options": ["A) 40%", "B) 50%", "C) 60%", "D) 70%"], "answer": "D"},
    {"category": "Địa lý", "question": "Quốc gia nào có diện tích lớn nhất thế giới?", "options": ["A) Mỹ", "B) Trung Quốc", "C) Nga", "D) Canada"], "answer": "C"},
    {"category": "Văn học", "question": "Ai là tác giả 'Tôi thấy hoa vàng trên cỏ xanh'?", "options": ["A) Nguyễn Nhật Ánh", "B) Tô Hoài", "C) Nam Cao", "D) Nguyễn Du"], "answer": "A"},
    {"category": "Lịch sử", "question": "Chiến dịch Điện Biên Phủ chấm dứt chế độ thực dân nào?", "options": ["A) Anh", "B) Pháp", "C) Mỹ", "D) Nhật"], "answer": "B"},
    {"category": "Toán học", "question": "Căn bậc hai của 64 là bao nhiêu?", "options": ["A) 6", "B) 7", "C) 8", "D) 9"], "answer": "C"},
    {"category": "Đố vui", "question": "Con gì có cánh mà không biết bay?", "options": ["A) Con gà", "B) Con vịt", "C) Cả hai", "D) Con ếch"], "answer": "C"},

]
